### ISSUE TITLE
Comisiones - Reports COLPR002.rdf y COLPR007.rdf

### ISSUE THREAD

**Issue by adip2002** [jpppina/migracion-galeno-art-forms11g#114]
Hola, buen dia.

Estoy probando la ultima version migrada a 11g de los reportes COLPR002.rdf y COLPR007.rdf y estoy viendo que el cuadro de Capitas y Contratos del Premio Productividad de Jefes de Empresas en la salida lo muestra partido en 2 paginas.

**Comment by adip2002** [comment]
Perdón, me faltaron mostrar las imágenes de las salidas de los reportes para mostrar las diferencias con respecto a la version Cliente-Servidor

![web124](https://cloud.githubusercontent.com/assets/14348364/13221629/21fdddaa-d95b-11e5-9b4f-c6ff9f154db6.png)

![web125](https://cloud.githubusercontent.com/assets/14348364/13221632/26ceb354-d95b-11e5-8029-ccbe78808819.png)

y en la version Cliente Servidor la salida correcta es 

![web126](https://cloud.githubusercontent.com/assets/14348364/13221643/346de1a6-d95b-11e5-93ec-c0669634820e.png)

Para que puedan identificar el reporte y los parametros ingresados para su salida les adjunto las siguientes imagenes.

![web127](https://cloud.githubusercontent.com/assets/14348364/13221745/9f289ffe-d95b-11e5-8e99-3427ce6e4e0e.png)

![web128](https://cloud.githubusercontent.com/assets/14348364/13221749/a30fa270-d95b-11e5-9f66-48d807b27463.png)

Muchas Gracias

**Comment by rleuzzi** [comment]
Tenia la propiedad "Print Object On"  en valor "Last Page" para varios campos. Ya fueron corregidos y se subieron las nuevas versiones a TEST. Volver a Testear. Gracias!!!

**Comment by adip2002** [comment]
Hola, buen dia.
Estoy probando este report en Test entrando en

http://art-weblogic-test:8888/forms/frmservlet?config=comisiones

Me logueo al sistema y luego desde el menu selecciono el repote con los parametros como muestra la imagen de mas abajo

![web130](https://cloud.githubusercontent.com/assets/14348364/13495203/1c16b45a-e128-11e5-838b-26bb478192b0.png)

cuando presiono el boton Ejecutar sale el siguiente error con lo cual no obtengo la salida

![web129](https://cloud.githubusercontent.com/assets/14348364/13495234/476f6dea-e128-11e5-95d5-6f9c911498f0.png)

Por favor lo pueden ver y me avisan cuando puedo volver a probar.

Muchas Gracias

**Comment by rleuzzi** [comment]
Parecería que los servicios de opmn del weblogic están bajos en el servidor. Ahora lo chequeamos y te comentamos.

**Comment by rleuzzi** [comment]
Estaba bajo el servicio WLS_REPORTS del weblogic. Ya lo levantamos. Volver a testear. Gracias!!!!

**Comment by adip2002** [comment]
Las pruebas por favor se pueden hacer en Desarrollo en vez de Test? les explico porque, estos reportes utilizan para mostrar liquidaciones de conceptos de comisión que no se configuraron y por ende no se corrieron en Test con lo cual no tengo datos para probar.
Me podrían dejar estos fuentes arreglados en Desa y los pruebo directamente en ese ambiente. Avisenme por favor. Muchas Gracias.

**Comment by rleuzzi** [comment]
Hola siempre lo subimos a DESA por defecto y a TEST si lo solicitan o sea que pueden probar sin problemas en DESA.

Saludos...

**Comment by adip2002** [comment]
Ahhh Ok, gracias Ruben, entonces lo pruebo en Desa y les aviso. Como nos habían dicho que probemos en Test ni prove en Desa porque pensé que no habían subido estas correcciones.
Muchas Gracias!!!!

**Comment by adip2002** [comment]
Listo gente, ahora si la salida de los reportes COLPR002.rdf y COLPR007.rdf es la correcta.

Muchas Gracias

**Comment by adip2002** [comment]
Hola, buen dia, omite decirles que por favor pases estos dos reportes (COLPR002.rdf y COLPR007.rdf) a Produccion debido a que ya estan arreglados.

Muchas Gracias
