### ISSUE TITLE
Comisiones - Reports COLPR018.rdf y COLPR020.rdf

### ISSUE THREAD

**Issue by adip2002** [jpppina/migracion-galeno-art-forms11g#115]
Los reports se generan bien y la salida es la correcta en la versión Web, pero cuando abre la salida del reports en pdf también abre un excel nuevo pero vacío, en la versión Cliente - Servidor esto no sucede, por favor lo podrían ver.

![image](https://cloud.githubusercontent.com/assets/14348364/13222541/1d7355ae-d95f-11e5-8058-dbc72385d684.png)

Muchas Gracias

**Comment by rleuzzi** [comment]
Por favor nos podrían indicar, como lo realizaron en el caso anterior, que reporte lanzan desde la pantalla de reportes y con que valores de parametros. Es para poder replicar el error y corregirlo.

Saludos...

**Comment by adip2002** [comment]
Hola, buen dia.

Las pruebas de estos 2 reportes por favor hacerlas en Desarrollo debido a que las liquidaciones de los conceptos de comision que utiliza este reporte para mostrar la información no se corrieron.

Un ejemplo de los parametros que utiliza el reporte COLPR020.rdf para correr es el siguiente

![web131](https://cloud.githubusercontent.com/assets/14348364/13496583/d13b48f8-e12f-11e5-96c1-bee594e0ee73.png)

Un ejemplo de los parametros que utiliza el reporte COLPR018.rdf para correr es el siguiente

![web132](https://cloud.githubusercontent.com/assets/14348364/13496865/4b9b4f20-e131-11e5-8bdb-a24297e3ddbb.png)

Saludos

**Comment by rleuzzi** [comment]
Hola, les cuento que esto se produce porque el parámetro PA_M_ABRIR_EXCEL este con valor "S" (también se ve en la imagen de la pantalla que nos envían).
Igualmente modificamos la librería cogli005.pll para que tenga en cuenta estos casos. Por ello solicitamos vuelvan a testear en DESA y también testeen algun otro reporte que si genere EXCEL para validar que el cambio aplicado no perjudico otros lanzamientos.

**Comment by adip2002** [comment]
Hola, los reportes COLPR018.rdf y COLPR020.rdf ahora se están generando correctamente y la salida es la correcta, pero por otro lado estuve probando otros reportes como me pidieron y hay reportes que una vez copiado el excel generado al disco local los abre automáticamente, ahora no lo esta haciendo.

Por ejemplo, los reportes COLPR012.rdf y COLPR016.rdf abren los excel una vez generados automáticamente, pero ahora no lo están haciendo

![web35](https://cloud.githubusercontent.com/assets/14348364/13581435/9c4d7266-e485-11e5-98ab-e5de4cd41342.png)

![image](https://cloud.githubusercontent.com/assets/14348364/13581527/11e1cdf6-e486-11e5-92f2-ee44fa5b0466.png)

![image](https://cloud.githubusercontent.com/assets/14348364/13581544/1fff0d68-e486-11e5-9296-0e17716db07f.png)

**Comment by rleuzzi** [comment]
Ahi agregamos un nuevo control. Pueden volver a testear ambos casos?. El que se corrigió y el que comenzó a funcionar diferente. Muchas Gracias!!!

**Comment by adip2002** [comment]
Listo, ahora si salen perfectamente todos los reportes con sus excel. Ambos casos fueron testeados y en ambos casos se comporta correctamente. Ya se podrían catalogar a Producción.

Muchas Gracias
