### ISSUE TITLE
Problemas de botones en la pantalla principal

### ISSUE THREAD

**Issue by XA45639** [jpppina/migracion-galeno-art-forms11g#119]
Los botones estándar de las pantallas están mal. Adjunto pantalla de ejemplo.
MENU-->ART_GDP001
Usuario: RIALM
 Pass: desaa002

**Comment by XA45639** [comment]
> [Print Pantalla GDP001.docx](https://github.com/jpppina/migracion-galeno-art-forms11g/files/289760/Print.Pantalla.GDP001.docx)

**Comment by rleuzzi** [comment]
Listo, volver a testear.
