### ISSUE TITLE
CIA: No se visualizan los iconos de la toolbar

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#125]
Aplicación CIA
Al ingresar a los ítem del menú, no se visualizan los iconos de la toolbar.
[No se visualizan los iconos de la toolbar.docx](https://github.com/jpppina/migracion-galeno-art-forms11g/files/291834/No.se.visualizan.los.iconos.de.la.toolbar.docx)

**Comment by rleuzzi** [comment]
Listo, volver a testear

**Comment by cynmiks** [comment]
Testeado Ok.
