### ISSUE TITLE
No Aparece <ENTER> Selección de Opción <F3> Nivel Anterior.

### ISSUE THREAD

**Issue by XA45639** [jpppina/migracion-galeno-art-forms11g#127]
Usuario: RIALM
 Pass: desaa002

No Aparecer el esta opción en la pantalla  "<ENTER> Selección de Opción <F3> Nivel Anterior".
en la pantalla Inferior. 

ESTO SUCEDE EN TODAS LAS PANTALLAS. Es decir que no muestran por ejemplo: 
<F5> Búsqueda, <Ctrl + Q>, ETC....

Ver documento adjunto
[5) No aparece F3 nivel anterior .docx](https://github.com/jpppina/migracion-galeno-art-forms11g/files/292038/5.No.aparece.F3.nivel.anterior.docx)

**Comment by rleuzzi** [comment]
Listo, Volver a testear.

**Comment by XA45639** [comment]
ok, listo!!!
