### ISSUE TITLE
pantalla RTP811 Laber por encima del Titulo Mapfre

### ISSUE THREAD

**Issue by XA45639** [jpppina/migracion-galeno-art-forms11g#128]
Usuario: RIALM
 Pass: desaa002

ARTManager --> Contratos --> Consultas --> Contratos

En la pantalla se vicualiza que en uno de los títulos de la grilla la Palabra MAPFRE esta superpuesta por el FRAME.

Adjunto error:
[6) RTP811 Palabra MAPFRE Tachada.docx](https://github.com/jpppina/migracion-galeno-art-forms11g/files/292100/6.RTP811.Palabra.MAPFRE.Tachada.docx)

**Comment by rleuzzi** [comment]
Listo Volver a testear.

**Comment by XA45639** [comment]
ok, listo!!!
