### ISSUE TITLE
Envíos – Error en pantalla principal

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#129]
Ambiente: ENVIOS
Usuario: FILIBERTOF/desaa002
Opción de menú: Al ingresar a la aplicación.
Error: Al ingresar a la aplicación de envíos, en el 6i, la pantalla principal aparece maximizada en cambio en la parte Web no.

**Comment by rleuzzi** [comment]
Podran subir una imagen comparativa porque no detectamos donde debe ir maximizado.

Muchas Gracias!!!!

**Comment by cynmiks** [comment]
Adjunto imagen.
![envios - pantalla principal](https://cloud.githubusercontent.com/assets/19472783/15861559/12c29e5c-2ca3-11e6-97da-e1dac0085c24.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Testeado OK.
