### ISSUE TITLE
Envíos – ENGPA000 - La datos de la grilla izquierda no figuran en negrita 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#142]
Aplicación: ENVIOS
Usuario: FILIBERTOF/desaa002
Opción de menú: Administración de Piezas / Re-Envio de Contenidos
Error: Los datos de la grilla de la parte izquierda no figuran en negrita. Solo figuran en negrita la fila  que se encuentra seleccionada. Adjunto imagen compartiva de ambos sistemas.
![grilla sin negrita](https://cloud.githubusercontent.com/assets/19472783/15745922/aaf56710-28aa-11e6-9804-84e14ae04da2.jpg)

**Comment by rleuzzi** [comment]
El atributo visual STANDARD_BOILERPLATE esta a nivel de bloque y solo para el registro actual por lo que el comportamiento correcto es el de la versión Web.

**Comment by cynmiks** [comment]
OK. Gracias!
