### ISSUE TITLE
Diferencia entre los reportes FORMS 6I vs WEB

### ISSUE THREAD

**Issue by XA45639** [jpppina/migracion-galeno-art-forms11g#160]
Usuario: H20348
Pass: desaa002

FORM: GDL101
Ruta: ARTManager -->Administracion de Prestadores --> Listados --> Tipo de prestadores

FORM: GDL102
ARTManager --> Cuentas a Pagar --> Tablas de cuentas a pagar --> Doc. Financial - Listado

Hay diferencias entre los reportes en la aplicación web vs Form 6I. 
La parte web sale con la letra pequeña y con un gran margen superior.

Este problema surge en los reportes:
- Tipo de prestadores
- Tipo de contratación
-  Puesto de prestadores / efectores

![diferencias entre reportes](https://cloud.githubusercontent.com/assets/19476286/16022242/45e569ba-318d-11e6-986a-b2a6b2a6077f.jpg)

**Comment by rleuzzi** [comment]
Deben quitar el tilde de "Ajustar pagina"  cuando envían a imprimir. Adjunto imágenes aclaratorias.
![con_tilde](https://cloud.githubusercontent.com/assets/14017610/16236904/64312ba6-37b0-11e6-9466-93f7a480bd82.jpg)
![sin_tilde](https://cloud.githubusercontent.com/assets/14017610/16236905/64349d04-37b0-11e6-83ca-9bb14f905e62.jpg)

**Comment by XA45639** [comment]
listo ok!!
