### ISSUE TITLE
CIA – Error en pantalla principal

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#162]
Título: CIA – Error en pantalla principal
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Al ingresar a la aplicación
Error: Al ingresar a la aplicación CIA, las pantallas son distintas. Adjunto imagen.

![cia - diferencias al ingresar a la aplicacion](https://cloud.githubusercontent.com/assets/19472783/16053058/88f11c8a-323d-11e6-8567-785272837f5f.jpg)

**Comment by rleuzzi** [comment]
Tanto el fuente ARHP000 como el fuente ARHLOGIN tienen imagenes de Consolidar como muestran las imagenes, por favor revisar las versiones de los fuentes.

![image](https://cloud.githubusercontent.com/assets/14017610/16239783/e0da1bf2-37bc-11e6-8aff-21d357d45543.png)

![image](https://cloud.githubusercontent.com/assets/14017610/16239803/ee3b949c-37bc-11e6-9fd6-08e44211f96a.png)

**Comment by cynmiks** [comment]
Se verificó y en ambos sistemas figura la misma pantalla.
