### ISSUE TITLE
CIA – Distinto funcionamiento al ingresar y solicitar el cambio de contraseña   

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#163]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Al ingresar a la aplicación
Error: Al ingresar a la aplicación CIA 6i,  me solicita el cambio de contraseña. Presiono CANCELAR, aparece un nuevo mensaje indicando “La clave del firewall no fue cambiada” y el presionar el botón ACEPTAR, sale de la aplicación. En cambio en la parte WEB, al ingresar también me solicita el cambio de contraseña, pero al presionar CANCELAR no aparece ningún mensaje y no sale de la aplicación. Adjunto documento con imágenes.
[CIA - Funcionalidad Cambio de Contraseña.docx](https://github.com/jpppina/migracion-galeno-art-forms11g/files/314635/CIA.-.Funcionalidad.Cambio.de.Contrasena.docx)

**Comment by rleuzzi** [comment]
El fuente arhpass.fmb en el boton cancelar solo tiene el siguiente codigo:

Exit_form(No_validate);

Eso genera que salga del form arhpass.fmb y quede en el form inicio ARHP000.fmb (comportamiento descripto en el word). Por ello y por la diferencia en las pantallas (imagenes) entendemos es un problema de version. Por favor validar version entregada para migrar.

**Comment by cynmiks** [comment]
Se verificó y funciona correctamente.
