### ISSUE TITLE
CIA – Pantalla de Cambio de Contraseña distintas   

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#164]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Aplicación / Cambiar la Password
Error: Las pantalla son distintas. Adjunto imagen.
![cia - diferencia en cambio de password](https://cloud.githubusercontent.com/assets/19472783/16081705/03220cb0-32e5-11e6-9414-ed845bd5fc21.jpg)

**Comment by rleuzzi** [comment]
Como explicamos en los issues anteriores, existe un evidente problema de versiones. Por favor revisar fuentes entregados para migrar.

**Comment by cynmiks** [comment]
Se verificó y figuran las mismas pantallas. Ok!
