### ISSUE TITLE
CIA – Diferencia en la barra de menu   

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#165]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Parámetros Generales
Form: ARHP024
Error: Al ingresar a la pantalla, las barras de menú son distintas. Adjunto imagen.
![cia - arhp024 - diferente botonera](https://cloud.githubusercontent.com/assets/19472783/16082842/5a24224c-32e9-11e6-8b87-20d42e033e5c.jpg)

Observaciones:  --

**Comment by rleuzzi** [comment]
Listo volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
