### ISSUE TITLE
CIA – ARHP024 – Diferencia en tecla F1     

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#166]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Parámetros Generales
Form: ARHP024
Error: En la aplicación 6i al presionar F1 aparece la siguiente pantalla en cambio en la aplicación Web no. Adjunto imagen.
![arhp024 - tecla f1](https://cloud.githubusercontent.com/assets/19472783/16082923/8a8e0a7e-32e9-11e6-9544-7b79bfae4987.jpg)

Observaciones:  --

**Comment by rleuzzi** [comment]
En web la tecla de ayuda es CTRL+H (F1 es una tecla que reserva el browser por eso no se puede usar).

**Comment by cynmiks** [comment]
Ok. Grs!
