### ISSUE TITLE
CIA – ARHP024 – Diferencia ítems del botón Ayuda     

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#167]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Parámetros Semáforo
Form: ARHP024
Error: 
• Al posicionarme en cualquier campo y presionar el botón Ayuda,  la cantidad de ítem visualizados en la ayuda es mayor en la aplicación Web. Además las pantallas son distintas. Adjunto imagen comparativa.
• En la aplicación 6i al presionar F1 aparece la pantalla de ayuda en cambio en la aplicación Web no.
Observaciones:  --

**Comment by rleuzzi** [comment]
No vemos imagen adjunta al issue. Igualmente como se explico en un issue anterior la tecja de ayuda en Web es CTRL+H.

**Comment by cynmiks** [comment]
Adjunto archivo con la diferencia en la cantidad de items en el menu ayuda.
[CIA - Diferencia en menu ayuda.docx](https://github.com/jpppina/migracion-galeno-art-forms11g/files/335540/CIA.-.Diferencia.en.menu.ayuda.docx)

**Comment by cynmiks** [comment]
Continua la diferencia en la cantidad de items en el menú ayuda.
