### ISSUE TITLE
CIA - ARHP004 - Diferencia en la barra de menú y tecla F1  

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#168]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Indicadores de Compañía
Form: ARHP004
Error: 
- Al ingresar a la pantalla la barra de menú son distintas.
- En la aplicación 6i al presionar F1 aparece la pantalla de ayuda en cambio en la aplicación Web no
  Observaciones: --

**Comment by rleuzzi** [comment]
Como detallamos en issue anterior, la tecla de ayuda es CTRL+H.

**Comment by cynmiks** [comment]
Ok con el error de F1, quedo entendido. Por favor, ver el otro error. Adjunto imagen
![cia - indicadores de compania](https://cloud.githubusercontent.com/assets/19472783/16424915/6519034e-3d38-11e6-8445-0e4a741a880d.jpg)

**Comment by cynmiks** [comment]
Agrego la etiqueta Done y lo dejo Pendiente de Test.

**Comment by cynmiks** [comment]
Testeado OK!
