### ISSUE TITLE
No salen los datos en el Form CPP102

### ISSUE THREAD

**Issue by XA45639** [jpppina/migracion-galeno-art-forms11g#169]
Usuario : H20348
Pass: desaa002

ARTManager --> Cuentas a Pagar --> Tablas de cuentas a pagar --> Personal habilitado autorizacion - actu

Al momento de elegir un dato de la lista de valores, este debe ser vista en la pantalla, pero esto no sucede..

Paso el print.

[20) no se ve los datos en la grilla.docx](https://github.com/jpppina/migracion-galeno-art-forms11g/files/316457/20.no.se.ve.los.datos.en.la.grilla.docx)

**Comment by rleuzzi** [comment]
Funciona correctamente, no vemos el problema. Adjuntamos imagen.

![image](https://cloud.githubusercontent.com/assets/14017610/16243833/838708a8-37cf-11e6-981e-8fa0e66dd252.png)
