### ISSUE TITLE
CIA – ARHP020 – Distintas barras de menú y funcionamiento de F1

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#171]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Agrupamiento de Indicadores
Form: ARHP020
Error: Al ingresar a la pantalla la barra de menú son distintas.
En la aplicación 6i al presionar F1 aparece la pantalla de ayuda en cambio en la aplicación Web no
Observaciones: --

**Comment by rleuzzi** [comment]
No vemos imagen adjunta al issue. Igualmente como se explico en un issue anterior la tecja de ayuda en Web es CTRL+H.

**Comment by cynmiks** [comment]
Ok con el errore de la tecla ayuda. Por favor, ver el error de la barra de menu. Adjunto imagen.
![cia - agrupamiento de indicadores](https://cloud.githubusercontent.com/assets/19472783/16425135/89ef6702-3d39-11e6-9d44-8cbed00c5fea.jpg)

**Comment by cynmiks** [comment]
Agrego la etiqueta Done y lo dejo Pendiente de Test para que cuando vuelvan a compilar toda la aplicación, ver el cambio en la barra de menú.

**Comment by cynmiks** [comment]
Testeado OK!
