### ISSUE TITLE
CIA – ARHP023 – Errores en pantalla Objetivos Presupuestos

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#172]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Objetivos Presupuesto
Form: ARHP023
Error: 
• 
![arhp023 - colores en la grilla](https://cloud.githubusercontent.com/assets/19472783/16091053/5338d22e-3308-11e6-9378-9f26710874a4.jpg)
Al ingresar a la pantalla la barra de menú son distintas.
• En la aplicación 6i al presionar F1 aparece la pantalla de ayuda en cambio en la aplicación Web no
• Los colores de la grilla son distintos. Adjunto imagen

**Comment by rleuzzi** [comment]
Los items que son de display y estan seleccionados se les asigna el atributo visual CG$INV_DISPLAY_ITEM_LOCK el cual posee color darkblue que es el que aparece en la imagen. Es correcto el funcionamiento.
No vemos imagen adjunta al issue. Igualmente como se explico en un issue anterior la tecla de ayuda en Web es CTRL+H.

**Comment by cynmiks** [comment]
Por favor, ver el error del menu. Adjunto imagen. 
![cia - objetivos presupuestos](https://cloud.githubusercontent.com/assets/19472783/16425313/65e14ae6-3d3a-11e6-9981-d805c789078f.jpg)

**Comment by cynmiks** [comment]
Agrego la etiqueta Done y lo dejo Pendiente de Test para que cuando vuelvan a compilar toda la aplicación, ver el cambio en la barra de menú.

**Comment by cynmiks** [comment]
Testeado OK!
