### ISSUE TITLE
CIA – ARHP027 – Errores en pantalla Objetivos Diarios

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#173]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Objetivos Diarios
Form: ARHP027
Error: 
• Al ingresar a la pantalla la barra de menú son distintas.
• En la aplicación 6i al presionar F1 aparece la pantalla de ayuda en cambio en la aplicación Web no
Observaciones: --

**Comment by rleuzzi** [comment]
No vemos imagen adjunta al issue. Igualmente como se explico en un issue anterior la tecla de ayuda en Web es CTRL+H.

**Comment by cynmiks** [comment]
Se adjunta imagen del error del menu. Grs!
![cia - objetivos diarios](https://cloud.githubusercontent.com/assets/19472783/16425443/1c5c712e-3d3b-11e6-86e1-d808cde17024.jpg)

**Comment by cynmiks** [comment]
Agrego la etiqueta Done y lo dejo Pendiente de Test para que cuando vuelvan a compilar toda la aplicación, ver el cambio en la barra de menú.

**Comment by cynmiks** [comment]
Testeado OK!
