### ISSUE TITLE
CIA – ARHP101 – Errores en Agrupamiento de Prestaciones

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#174]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Agrupamiento de Prestaciones
Form: ARHP101
Error: 
• Al ingresar a la pantalla la barra de menú son distintas.
• En la aplicación 6i al presionar F1 aparece la pantalla de ayuda en cambio en la aplicación Web no
• Los colores de la grilla son distintos. Adjunto imagen.

Observaciones: --

[ARHP101 - Distintos colores en la grilla.docx](https://github.com/jpppina/migracion-galeno-art-forms11g/files/316796/ARHP101.-.Distintos.colores.en.la.grilla.docx)

**Comment by rleuzzi** [comment]
Los items que son de display y estan seleccionados se les asigna el atributo visual CG$INV_DISPLAY_ITEM_LOCK el cual posee color darkblue que es el que aparece en la imagen. Es correcto el funcionamiento.
No vemos imagen adjunta al issue. Igualmente como se explico en un issue anterior la tecla de ayuda en Web es CTRL+H.

**Comment by cynmiks** [comment]
Adjunto imagen del menu. Grs
![cia - agrupamiento de prestaciones](https://cloud.githubusercontent.com/assets/19472783/16426955/97696830-3d41-11e6-8768-e33ef4b3f99d.jpg)

**Comment by cynmiks** [comment]
Agrego la etiqueta Done y lo dejo Pendiente de Test para que cuando vuelvan a compilar toda la aplicación, ver el cambio en la barra de menú.

**Comment by cynmiks** [comment]
Ok!
