### ISSUE TITLE
CIA – ARHP600 – Errores en Pantalla Item Costos Medicos  

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#175]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Items Costo Medico
Form: ARHP600
Error: 
• Al ingresar a la pantalla la barra de menú son distintas.
• En la aplicación 6i al presionar F1 aparece la pantalla de ayuda en cambio en la aplicación Web no

Observaciones: --

**Comment by rleuzzi** [comment]
No vemos imagen adjunta al issue. Igualmente como se explico en un issue anterior la tecla de ayuda en Web es CTRL+H.

**Comment by cynmiks** [comment]
Adjunto imagen del menu. Grs.
![cia - item costos medicos](https://cloud.githubusercontent.com/assets/19472783/16427105/3e1209e4-3d42-11e6-9f81-6e3af36fedb7.jpg)

**Comment by cynmiks** [comment]
Agrego la etiqueta Done y lo dejo Pendiente de Test para que cuando vuelvan a compilar toda la aplicación, ver el cambio en la barra de menú.

**Comment by cynmiks** [comment]
Testeado OK!
