### ISSUE TITLE
CIA – ARHP610 – Errores en Pantalla Mantenimiento de Descripciones  

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#176]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Mantenimiento de Descripciones
Form: ARHP610
Error: 
• Al ingresar a la pantalla la barra de menú son distintas.
• En la aplicación 6i al presionar F1 aparece la pantalla de ayuda en cambio en la aplicación Web no

Observaciones: --

**Comment by rleuzzi** [comment]
No vemos imagen adjunta al issue. Igualmente como se explico en un issue anterior la tecla de ayuda en Web es CTRL+H.

**Comment by cynmiks** [comment]
Se adjunta imagen compartiva del menu. Grs
![cia - mantenimiento de descripciones](https://cloud.githubusercontent.com/assets/19472783/16427244/c9da3820-3d42-11e6-8828-f8d198385c14.jpg)

**Comment by cynmiks** [comment]
Agrego la etiqueta Done y lo dejo Pendiente de Test para que cuando vuelvan a compilar toda la aplicación, ver el cambio en la barra de menú.

**Comment by cynmiks** [comment]
Testeado OK!
