### ISSUE TITLE
ART - No aparece Pantalla ARLPA001

### ISSUE THREAD

**Issue by XA45639** [jpppina/migracion-galeno-art-forms11g#177]
No aparece la pantalla

usuario: H20348
pass: desaa002

Ruta
ARTManager --> Cuentas a Pagar --> Tablas de cuentas a pagar --> Carga de Formatos Diarios de Archivos

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by XA45639** [comment]
listo ok
