### ISSUE TITLE
ART - NO aparece la pantalla ARLPI029

### ISSUE THREAD

**Issue by XA45639** [jpppina/migracion-galeno-art-forms11g#178]
No aparece la pantalla

Usuario: H20348
pass: desaa002

Ruta:
ARTManager --> Cuentas a Pagar --> Tablas de cuentas a pagar --> Motivos y Soluciones de Anulaciones

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by XA45639** [comment]
listo ok.
