### ISSUE TITLE
CIA – ARHP030 – ABM Tasas Recargos 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#198]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Parámetros del Sistema / Tasas y recargos / ABM Tasas Recargos
Form: ARHP030
Error: 
• Distintas letras en el frame. Adjunto imgen.
![cia - abm tasas recargos - letras](https://cloud.githubusercontent.com/assets/19472783/16530558/12ad67da-3f9f-11e6-8a7b-b8a2763f5c22.jpg)

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas
o   Al posicionarme en la columna Vigencia Desde o Vigencia Hasta en el calendario faltan los nombres a los botones.
o   Al posicionarme en la columna Segmento, la lista de valores es chica.

Observaciones:

**Comment by cynmiks** [comment]
Continua el error del distinto tipo de letra. Los demás errores fueron corregidos.

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
