### ISSUE TITLE
CIA – ARHP009 – Costos Estimados de Diagnósticos  

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#200]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Mantenimiento de Entidades / Costo Estimado de diagnósticos
Form: ARHP009
Error: 
• Parte de la pantalla queda en gris. Adjunto imagen.
![cia - costo estimado de diagnosticos](https://cloud.githubusercontent.com/assets/19472783/16530759/fa719ce4-3f9f-11e6-884a-c1f90fe4fd4d.jpg)

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas

Observaciones:

**Comment by cynmiks** [comment]
Continua el error. La pantalla queda en gris.

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
