### ISSUE TITLE
CIA – ARHP026 – Ubicaciones Regionalizaciones   

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#203]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Mantenimiento de Entidades / Regionalización / Ubicaciones y regionalización
Form: ARHP026
Error: 
• Al presionar F9 en campo Cliente, aparece la LOV, al seleccionar algún clientes en el aplicación 6i desaparece, en cambio en ARTWEB se visualiza altras. Adjunto imagen.

![cia - ubicaciones lov](https://cloud.githubusercontent.com/assets/19472783/16531364/872016d2-3fa2-11e6-8ad7-ecda635f737c.jpg)

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas

Observaciones:

**Comment by cynmiks** [comment]
Continúa el error: 

Al presionar F9 en campo Cliente, aparece la LOV, al seleccionar algún clientes en el aplicación 6i desaparece, en cambio en ARTWEB se visualiza atrás.  (La imagen se encuentra en el primer comentario)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
