### ISSUE TITLE
CIA – ARHP320 – Zonas 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#208]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Mantenimiento de Entidades / Regionalización / Zonas
Form: ARHP320
Error: 
• Al presinar SHIFT + TAB, sale de la pantalla y se abre la pantalla del botón exportar al excel. Intento cerrarla y se genera el siguiente error. Adjunto imagen.En cambio en la aplicación 6i queda posicionado en el primer campo del formulario.Similar funcionamiento tiene en otros forms. 

![cia - zonas](https://cloud.githubusercontent.com/assets/19472783/16568521/9ee0df2a-4201-11e6-8762-b9338d57f087.jpg)

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas

Observaciones:

**Comment by cynmiks** [comment]
Continua el siguiente error: (ver primer comentario)

Al presinar SHIFT + TAB, sale de la pantalla y se abre la pantalla del botón exportar al excel. Intento cerrarla y se genera el siguiente error. Adjunto imagen.En cambio en la aplicación 6i queda posicionado en el primer campo del formulario.Similar funcionamiento tiene en otros forms.

**Comment by rleuzzi** [comment]
Esto ocurre porque no hay bloque seleccionado en la pantalla de exportación a excel. Se debe siempre elegir un bloque porque por código intenta navegar al primer bloque navegable pero si es null da error. Si navegan a la pantalla de excel apretando el botón correspondiente de la toolbar verán que no ocurre el error. Tampoco si seleccionan un bloque y luego dan al botón retornar. Por favor validar.

**Comment by cynmiks** [comment]
En la grilla presionas TAB y luego SHIFT+TAB,  en la aplicación 6i queda posicionado en la primera celda de la grilla. (ver imagen). En cambio en la aplicación WEB, se va a otro bloque y genera esos errores. El SHIFT+TAB debería finalizar en la primera celda al igual que la aplicación 6i. +

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
