### ISSUE TITLE
CIA – ARHP006  -- Tomar Foto de Indicadores  

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#211]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / Indicadores / Tomar Foto de Indicadores
Form: ARHP006
Error: 
• En la Aplicación 6i se generó un árbol de directorios en C:\FOTO En la aplicación Web aparece no hace nada.Adjunto imagen

![c_foto](https://cloud.githubusercontent.com/assets/19472783/16597670/8a942a70-42d0-11e6-911a-6d8f716a945c.jpg)

**Comment by cynmiks** [comment]
Continua el error. En la parte Web no se genera el árbol de directorios.

**Comment by rleuzzi** [comment]
El código intenta crear un bat, en tiempo de ejecución, en el directorio c:\ y existen problemas de permiso cuando se ejecuta en formato Web (políticas de seguridad de Java). Se cambio a c:\temp y funciona correctamente. Volver a testear.

**Comment by cynmiks** [comment]
Con el cambio se generó el árbol de directorios pero aparece el siguiente error varias veces hasta que llega el ultimo mensaje con la leyenda "El proceso de Generación de Archivos ha finalizado"

![cia_arhp006_error](https://cloud.githubusercontent.com/assets/19472783/18551178/b8c9b33e-7b2d-11e6-8e1a-e98aa0c11e88.jpg)

**Comment by rleuzzi** [comment]
Existe ese directorio en la PC del usuario que ejecuta el proceso?. El bat que se genera en tiempo de ejecución necesita esa ruta como muestra el código a continuación.

  CLIENT_TEXT_IO.putf(fd, 'del   '||:cg$ctrl.ddirect||'\MEDICA\'||to_char(:cg$ctrl.fgestion)||'*.htm\n'); 
    dline := 'C:\orawin95\DISCVR4\DIS4USR  /OPEN '||direct||'\IndGciaMedica.DIS /CONNECT '||dusr|| 
             ' /EXPORT HTML '||:cg$ctrl.ddirect||'\MEDICA\'||to_char(:cg$ctrl.fgestion)||'\'||dlst|| 
             ' /SHEET ALL /BATCH /PARAMETER NPeriodo '||to_char(:cg$ctrl.fgestion) 
             ; 
    CLIENT_TEXT_IO.putf(fd, 'start /w '||dline||'\n');

**Comment by cynmiks** [comment]
Ok! No existe el directorio y un error similar se generar en la aplicación 6i.
