### ISSUE TITLE
CIA – ARHP500  -- UART 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#212]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / Indicadores / UART
Form: ARHP500
Error: 
• Al presionar TAB varias veces, la pantalla termina mostrando parte de una pantalla. Adjunto imagen.

![arhp500](https://cloud.githubusercontent.com/assets/19472783/16597730/cc5a246e-42d0-11e6-99c6-ade79169e5b4.jpg)

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas

**Comment by cynmiks** [comment]
Esta pantalla continua con errores:
-   Posee distintos formatos de letra. Adjunto imagen comparativa.

![cia_arhp500 - distintos tipos de letra](https://cloud.githubusercontent.com/assets/19472783/18315842/d3f38594-74ee-11e6-97fe-3bbee10fecc9.jpg)
-   Al presionar 2 veces TAB, aparece parte de una pantalla que no aparece en la aplicación 6i. Adjunto imagen.

![cia_arhp500 - pantalla despues del tab](https://cloud.githubusercontent.com/assets/19472783/18315862/e1d61424-74ee-11e6-90e6-b3cdf841dd3f.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Los errores de los distintos formatos de letra y al presionar 2 veces TAB, aparece parte de una pantalla que no aparece en la aplicación 6i fueron corregidos. 
Pero al presionar el botón "Generar archivo" aparecen los siguientes errores y además el tiempo en aparecer dicho error es bastante superior a la aplicación 6i.

![cia - arhp500_error report](https://cloud.githubusercontent.com/assets/19472783/18556128/c6461ba2-7b40-11e6-9f51-d49c0124b61b.jpg)

**Comment by rleuzzi** [comment]
Volver a testear.

**Comment by cynmiks** [comment]
El error no se produce pero no puedo volver a testear el tiempo ya que en la aplicación 6i, actualmente no se abre la pantalla.
