### ISSUE TITLE
CIA – ARHP100  -- Detección de anomalías 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#213]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / D2A / Detección de anomalías
Form: ARHP100
Error: 
• Al presionar TAB varias veces y luego Shift + TAB la pantalla termina mostrando parte de una pantalla. Adjunto imagen.
![arhp100](https://cloud.githubusercontent.com/assets/19472783/16628499/5d8791bc-4388-11e6-8ea6-3fe64cf053f6.jpg)

• Se ejecuta una búsqueda, por ejemplo con las siguientes condiciones. Adjunto imagen.

![arhp100_busqueda](https://cloud.githubusercontent.com/assets/19472783/16628503/63986efa-4388-11e6-81dc-fe0a6a3735a6.jpg)

Al presionar el botón mostrar los casos, aparece otra pantalla con los casos. Se presiona TAB y aparece un reporte. En el mismo, existen diferencias (adjunto imagen)

![arhp100_previewer](https://cloud.githubusercontent.com/assets/19472783/16628516/6d23bae2-4388-11e6-9243-2af58878b388.jpg)

o   La imagen del reporte, arriba a la izquierda. 
o   Lineas punteadas 

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas
o   El calendario faltan los nombres a los botones.

**Comment by cynmiks** [comment]
Continúan los siguientes errores:
• Al presionar TAB varias veces y luego Shift + TAB la pantalla termina mostrando parte de una pantalla (ver imagen en el primer comentario)
• Se ejecuta una búsqueda, por ejemplo con las siguientes condiciones. (Ver imagen en el primer comentario). Al presionar el botón mostrar los casos, aparece otra pantalla con los casos. Se presiona TAB y debe aparece el error **FRM-41214:Unable to run report.** Y luego el siguiente error (adjunto imangen).

![oracle_reports_services_servlet](https://cloud.githubusercontent.com/assets/19472783/18318096/a7c3dfb6-74f6-11e6-84a5-9d6f70b50849.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Se corrigieron los errores mencionados. Testeado OK!
