### ISSUE TITLE
CIA – ARHP110  -- Seguimientos 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#214]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / D2A / Seguimientos
Form: ARHP110
Error: 
• Al ingresar el nro de caso, en la aplicación 6i figura en negrita algunos campos, en cambio en ARTWEB no. Adjunto imagen. 

![arhp110](https://cloud.githubusercontent.com/assets/19472783/16628550/918678b6-4388-11e6-8143-feda4787a83c.jpg)

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas
o   El calendario faltan los nombres a los botones.

**Comment by cynmiks** [comment]
Continua el error en los campos en negrita.

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
