### ISSUE TITLE
CIA – ARHP121  -- Reportes de casos abiertos 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#215]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / D2A / Reportes de casos abiertos
Form: ARHP121
Error: 
• Se genera un reporte con las siguientes condiciones, y en el mismo surgen diferencias en el tipo de letra y en el logo del reporte. Adjunto imagen.

![arhp121](https://cloud.githubusercontent.com/assets/19472783/16628597/c8f0676c-4388-11e6-89bb-7885ac5c7816.jpg)

![arhpr120_previewer](https://cloud.githubusercontent.com/assets/19472783/16628602/cc2bb774-4388-11e6-9736-139bcda933db.jpg)

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas
o   El calendario faltan los nombres a los botones.

**Comment by cynmiks** [comment]
Ahora no se visualiza el reporte. Aparece el error FRM-41214-Unable to run report.

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Se visualiza el reporte, pero tienen distinto formato de letra. Adjunto imagen.

![arhpr120_previewer - nuevo](https://cloud.githubusercontent.com/assets/19472783/18594771/f81898b2-7c17-11e6-9129-d3fcc5d59386.jpg)

**Comment by cynmiks** [comment]
Mail a Luis para que nos indique si se deben o no modificar las letras de los reports.

**Comment by cynmiks** [comment]
Se cierra. Mail de Jose del 19/09.
