### ISSUE TITLE
CIA – ARHP410  -- Grupos 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#218]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / DU / ABM de Grupos
Form: ARHP410
Error: 
• La LOV de Contratos posee distinto formato de fecha. Adjunto imagen.
![arhp410_lov formato fecha](https://cloud.githubusercontent.com/assets/19472783/16628950/37cfd91e-438a-11e6-95ed-9fe2165f7bfc.jpg)

• En todos los campos de fechas no posee asigando el calendario.
• Falta el Boton “Gastos que no se cobran”
![arhp410_falta boton](https://cloud.githubusercontent.com/assets/19472783/16628958/3f001adc-438a-11e6-96a5-aa41480b2c80.jpg)

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas

**Comment by cynmiks** [comment]
Continua el error en la LOV de contratos. Posee distintos tipos de fechas. Ver imagen en el primer comentario

**Comment by rleuzzi** [comment]
Cuando se puso en produccion Wallstreet, Juan y Alejandro definieron que todos los sistemas tengan como default NLS_DATE_FORMAT=DD/MM/YYYY. Por ello todos los archivos de environment poseen esa definicion y eso genera que la fecha de la lov tenga ese formato.

**Comment by cynmiks** [comment]
Ok!
