### ISSUE TITLE
CIA – ARHP465  -- Provisión 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#220]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / DU / Provisión
Form: ARHP465
Error: 
• El formato de las letras son distintas.
• Las etiquetas tienen distintos nombres.
• No me permite seleccionar el checklist
• Al presionar el botón de la carpeta, abre la lista de directorios en distinas.

![lemcked_dwh_arhp465](https://cloud.githubusercontent.com/assets/19472783/16664781/132bd6d4-4458-11e6-90fc-f597ecbd9eaa.jpg)

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas

**Comment by cynmiks** [comment]
Continúan los siguientes errores:
- El formato de la letra es distinto.
  ![cia - arhp465_autorizar_provision](https://cloud.githubusercontent.com/assets/19472783/18352228/ebe7a3ae-75b3-11e6-9595-90d171f7cd67.jpg)
- Al correr la barra inferior a la izquierda, aparece toda la pantalla en gris.
  ![cia - arhp465 - pantalla en gris](https://cloud.githubusercontent.com/assets/19472783/18352249/0225481a-75b4-11e6-9ff3-e4128a992a52.jpg)
- Al presionar el botón de la carpeta, abre la lista de directorios en distinas. (ver primer comentario)

**Comment by rleuzzi** [comment]
Listo, volver a testear. 
Respecto al botón de la carpeta la primera vez el campo :control.d_path es nulo por lo que la ventana se abre en la ventana por defecto del usuario (asi lo resuelve el componente Java nuevo) luego si se toma una carpeta, la próxima vez abre en esa carpeta. La apertura original cuando el StartDirectory es nulo no la podemos cambiar porque es comportamiento propio de Webutil por lo que funcionara de esa forma.

**Comment by cynmiks** [comment]
Testeado OK!
