### ISSUE TITLE
CIA – ARHP475  -- Reporte de Consolidacion 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#221]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / DU / Provisión
Form: ARHP475
Error: 
• Los reportes tienen distintos logos de la companía

Al igual que en otros issues: 
o   Al ingresar a la pantalla la barra de menú son distintas

Observaciones:

**Comment by cynmiks** [comment]
Los reportes poseen distintos tipos de letras.

![cia - arhpr015_previewer](https://cloud.githubusercontent.com/assets/19472783/18352796/31eeda1e-75b6-11e6-8c1a-ba13dd844aac.jpg)

**Comment by rleuzzi** [comment]
Los tipos de letras, si no se utiliza Arial, sera difícil sean exactas porque son dos entornos diferentes (Windows y Oracle Linux). Ademas si la font utilizada no esta cargada en Linux, reports la reemplaza por una aproximación. Si el cambio no es sumamente significativo y no altera el normal funcionamiento lo recomendable es que quede así. Discutirlo con Juan.

**Comment by cynmiks** [comment]
Mail a Luis para que nos indique si se deben o no modificar las letras de los reports.

**Comment by cynmiks** [comment]
Se cierra. Mail de Jose del 19/09.
