### ISSUE TITLE
CIA – ARHP452 -- Gastos que no se cobran a la cláusula 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#222]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / DU / Gastos que no se cobran a la clausula
Form: ARHP452
Error: 
• No existe el ítem del menú para acceder
![menu_principal_](https://cloud.githubusercontent.com/assets/19472783/16666014/26d83b06-445c-11e6-9209-19b4fda6feb3.jpg)

Observaciones:

**Comment by cynmiks** [comment]
Siguen sin figurar esos punto de menú.

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
