### ISSUE TITLE
CIA – ARHP462 – De liquidado a pagado 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#223]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / DU / De liquidado a pagado
Form: ARHP462
Error: 
• No existe el ítem del menú para acceder

![menu_principal_](https://cloud.githubusercontent.com/assets/19472783/16666044/4bbe511c-445c-11e6-9153-fb1a4cd0fdff.jpg)

Observaciones:

**Comment by cynmiks** [comment]
Sigue sin figurar ese ítem de menú.

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
