### ISSUE TITLE
CIA – ARHP460  -- Liquidacion 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#230]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / PU / Liquidacion
Form: ARHP460
Error: 
• No figura el botón “De liquidado a Pagado”
![arhp460_falta boton](https://cloud.githubusercontent.com/assets/19472783/16814237/53806210-490b-11e6-914d-26143f80435c.jpg)

• El formato de las fechas es distinto
![arhp460_fechas](https://cloud.githubusercontent.com/assets/19472783/16814243/57a696f2-490b-11e6-8070-23589c816eef.jpg)

• Al presionar el botón de la carpeta, en 6i aparecen los directorios de la red, en cambio en artweb 
![arhp460_arbol](https://cloud.githubusercontent.com/assets/19472783/16814246/5ccde77a-490b-11e6-8348-209933eda4f9.jpg)

• El presionar el botón “Procesar”, en 6i se abre un reporte en cambio en artweb sale un error.

**Comment by cynmiks** [comment]
Esta pantalla continua con los siguientes errores (ver primer comentario)
-  El formato de las fechas es distinto
- Al presionar el botón de la carpeta, en 6i aparecen los directorios de la red, en cambio en artweb

**Comment by rleuzzi** [comment]
El formato de fecha se detallo en un issue anterior (formato solicitado por Juan y Alejandro para todos los sistemas, fue agregado como variable de entorno en archivos de environment).
Respecto al botón carpeta, también se detallo en issue anterior que al ser el StartDirectory nulo (la primera vez) abre en la carpeta defecto para el usuario que ejecuta el aplicativo (esto lo maneja Oracle Webutil y Java de esta forma).

**Comment by cynmiks** [comment]
OK!
