### ISSUE TITLE
COBRA – cbabmusu – Gestores 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#236]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Tablas > Usuarios
Form: cbabmusu
Error: No se abre la pantalla del menu.
Observaciones:

**Comment by cynmiks** [comment]
Continua el error.

**Comment by rleuzzi** [comment]
No compila porque no ve los objetos:

CGT_EMPLEADOS_CONSOLIDAR
CGT_EMPLEADOS_EXTERNOS

**Comment by cynmiks** [comment]
Fueron otorgados los permisos en Desa. Por favor, volver a compilar. Gracias!

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
