### ISSUE TITLE
COBRA – cbusuges – Gestores 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#237]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Tablas > Usuario-Agencia/Gestor
Form: cbusuges
Error: No se abre la pantalla del menu.
Observaciones:

**Comment by cynmiks** [comment]
Continua el error.

**Comment by rleuzzi** [comment]
No compila porque no ve el objeto "CGT_EMPLEADOS_EXTERNOS".

**Comment by cynmiks** [comment]
Fueron otorgados los permisos en Desa. Por favor, volver a compilar. Gracias!

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Testeado OK. Aclaración: la pantalla no devuelve datos en ambos sistemas.
