### ISSUE TITLE
COBRA – cboconfil – Consulta de cartas a Emitir 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#255]
Ambiente: COBRA
Usuario: APARICIOJ/Desaa001
Opción de menú: Procesos > Cartas > Cartas a emitir
Form: cboconfil
Error: 
-   Los colores de los botones son distintos. 

![cboconfil_botones](https://cloud.githubusercontent.com/assets/19472783/17554159/fe1fed0a-5edf-11e6-9505-6017ff134c71.jpg)
-   Botón “Impresión de Listado” se produce un error en ambos sistemas.
-   Botón “Generar” se produce un error en ambos sistemas

Observaciones:

**Comment by cynmiks** [comment]
Continúan los errores.

**Comment by rleuzzi** [comment]
Solucionado el tema de los colores, el resto de los errores, los hereda de la version anterior

**Comment by cynmiks** [comment]
OK. Se corrigió el color de los botones. Con respecto a los botones Impresión de Listado y Generar se probó con el contrato 2037 y se funcionaron OK (en ambos sistemas se genero un error "Problemas al abrir el archivo C:\ARTM\CM_SUCURSALES_CENTRO/NOA.TXT"
