### ISSUE TITLE
COBRA – cbgenimp  – Generación e impresión de Cartas en forma masiva e individual   

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#256]
Ambiente: COBRA
Usuario: APARICIOJ/Desaa001
Opción de menú: Procesos > Cartas > Generar / Imprimir
Form: cbgenimp  
Error: 
-   El botón “Generar impresión” tiene un icono distinto.
-   Al presionar TAB + Control la aplicación 6i cambia de solapa, en cambio la aplicación ARTWEB no.
  ![cbgenimp](https://cloud.githubusercontent.com/assets/19472783/17554480/60ee09d4-5ee1-11e6-9e08-99ff38bb998b.jpg)

Observaciones:

**Comment by cynmiks** [comment]
Continúan los errores.

**Comment by rleuzzi** [comment]
En version Web el cambio de solapa se realiza con CTRL + Flecha Der o Flecha Izq
El icono es el correcto en base a los archivos ico que nos pasaron. Adjunto muestra de imprimir.ico
![image](https://cloud.githubusercontent.com/assets/14017610/19282286/054559fc-8fc4-11e6-94f7-3d91fdebb01e.png)

**Comment by jpppina** [comment]
El ícono, tienen dos hojas, en la primera está el icono que queremos usar y en la segunda, el icono que finalmente quedó. Estamos viendo si armamos o pasamos un ícono nuevo. si tienen otra opción para solucionar el problema, nos avisan.

**Comment by rleuzzi** [comment]
Listo, se creo el gif correspondiente, se rearmo, firmo y deployo la jar de iconos nueva y se reinicio el servidor para que tome los cambios. Volver a testear.

**Comment by cynmiks** [comment]
Testeado OK
