### ISSUE TITLE
COBRA – cbcarres – Contratos a Rescindir 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#257]
Ambiente: COBRA
Usuario: APARICIOJ/Desaa001
Opción de menú: Procesos > Cartas > Rescisión de contratos
Form: cbcarres
Error: No se abre la pantalla de dicho menú.
Observaciones:

**Comment by cynmiks** [comment]
Continúan los errores.

**Comment by rleuzzi** [comment]
El fuente CBCARRES no se encuentra entre los objetos entregados para migrar

**Comment by jpppina** [comment]
Se habló con Florencia y esta opción no se va a usar más. lo van a eliminar del menú.
