### ISSUE TITLE
COBRA – cbgesmas – Asignacion masiva de cuentas 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#258]
Ambiente: COBRA
Usuario: APARICIOJ/Desaa001
Opción de menú: Procesos > Asignación de gestores > Redistribución
Form: cbgesmas
Error: No se abre la pantalla de dicho menú.
Observaciones:

**Comment by cynmiks** [comment]
Continúan los errores.

**Comment by rleuzzi** [comment]
El form no compila porque el usuario ldrcobra no ve la tabla ARF_FU_RESC_FALTA_PAGO

**Comment by jpppina** [comment]
Se corrigieron los permisos en desarollo, ya debería compilar

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Se testeó la pantalla:

1-En la versión 6i la pantalla aparece maximizada.
2-En botón Archivo tiene otro color y luego al realizar la búsqueda, el botón Procesar también tiene otro color.

![asignacion_masiva_de_cuentas](https://cloud.githubusercontent.com/assets/19472783/20392500/e74fdbec-acb6-11e6-8bd0-29a14390df22.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a revisar. Los botones tenian Foreground Color "darkred". Se les modifico a "Black".

**Comment by cynmiks** [comment]
Testeado OK.
