### ISSUE TITLE
COBRA – cbchecon  – Consulta de cheques 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#259]
Ambiente: COBRA
Usuario: APARICIOJ/Desaa001
Opción de menú: Procesos > Consultas > Cheques
Form: cbchecon  
Error: Se realiza una búsqueda, por ejemplo, contrato 1. Luego, al presionar el botón “Imputaciones” se abre una pantalla donde el tipo de letra es distinta. 

![cbchecon](https://cloud.githubusercontent.com/assets/19472783/17625012/647c5126-607d-11e6-80d5-340adef4741d.jpg)

**Comment by cynmiks** [comment]
Continua el error.

**Comment by rleuzzi** [comment]
El tema es que el tipo de letra usado en estos labels es Fixedsys y al no tener la compatibilidad en Linux y Java, Forms la transforma a lo mas parecido. En este caso Arial. Recuerden que los tipos de letras compatibles entre los tres entornos (Windows, Linux y Maquina Virtual) son limitados.

**Comment by cynmiks** [comment]
Ok.
