### ISSUE TITLE
COBRA – cbabmrco – Recupero de Cotizaciones 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#260]
Ambiente: COBRA
Usuario: APARICIOJ/Desaa001
Opción de menú: Procesos > Recuperos de Cotizaciones > Administracion de Recuperos
Form: cbabmrco
Error: No se abre la pantalla de dicho menú
Observaciones:

**Comment by cynmiks** [comment]
Continua el error.

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Se testeo la pantalla y figuran los siguientes errores:

1- En la version 6i la pantalla aparece maximizada, en cambio en la version web no.

**Comment by rleuzzi** [comment]
El codigo para maximizar la ventana no esta pero se agrego al WHEN-NEW-FORM-INSTANCE. Volver a testear.

**Comment by cynmiks** [comment]
Testeado OK
