### ISSUE TITLE
COBRA – cbconrco – Consulta de Recuperos 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#261]
Ambiente: COBRA
Usuario: APARICIOJ/Desaa001
Opción de menú: Procesos > Recuperos de Cotizaciones > Consulta de Recuperos
Form: cbconrco
Error: No se abre la pantalla de dicho menú
Observaciones:

**Comment by cynmiks** [comment]
Continua el error.

**Comment by rleuzzi** [comment]
El fuente no compila porque el usuario LDRCOBRA no ve la Tabla CAT616

**Comment by jpppina** [comment]
Se corrigieron los permisos en desarollo, ya debería compilar

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Ahora se abre la pantalla pero con los siguientes errores:

1-La LOV del campo Usuarios es demasiado grande.
2-En la solapa Archivo, es distinto el icono del botón. 
![cobra-boton archivo](https://cloud.githubusercontent.com/assets/19472783/20360350/1e73398e-ac12-11e6-928b-57d59dc42875.jpg)

3-En la solapa Listado, es distinto el icono del botón.
![cobra - boton listado](https://cloud.githubusercontent.com/assets/19472783/20360355/23a6ff80-ac12-11e6-9b04-4a48a40f5698.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a testear. Recordar el tema de los iconos. En este caso agrandamos un poco el icono (mas de 18x20) porque el botón asociado es mas grande. La lov se corrigió el problema fue que se agrando automáticamente como solicitaron para lovs pequeñas pero el sistema de coordenadas de este form era diferente.

**Comment by cynmiks** [comment]
Testeado OK!
