### ISSUE TITLE
CIA - Menu Indicadores

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#263]
Ambiente: CIA
Usuario: LEMCKED/a1234567
Opción de menú: Gestión del sistema / Indicadores 
Error: En todos los items de menu que se indican aparece el mismo error:

![menu indicadores](https://cloud.githubusercontent.com/assets/19472783/18351070/0d5139ec-75af-11e6-9f3d-efea4123c70b.jpg)

**Comment by rleuzzi** [comment]
Volver a testear.

**Comment by cynmiks** [comment]
No aparece el error, pero no se que hace ese item de menu. Mail a Luis
