### ISSUE TITLE
COBRA – cbbonint – Bonificación de interés 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#266]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Procesos > Bonificación de intereses
Form: cbbonint
Error: 
• La barra de menú es distinta.
![cobra - bonificacion_de_intereses - menu](https://cloud.githubusercontent.com/assets/19472783/18717229/aee46608-7ff5-11e6-9c39-8748eab6d5b7.jpg)

• Con CTRL+TAB en la versión 6i, se mueve en la grilla, en cambio en la versión Web, la pantalla desaparce.
• En el campo Cliente, al presionar F9 se abre una LOV que ocupa toda la pantalla.
Observaciones:

**Comment by rleuzzi** [comment]
Recordar que no se debe apretar Ctrl+Tab porque es un shortcut tkey utilizado por el Browser de internet para navegar por las solapas. En el caso de Forms activa el trigger WHEN-WINDOW-DEACTIVATED.

Si deseamos navegar por los items las teclas son Tab y Shift+Tab (next item y previous item).

Corregido el tema de la toolbar. Volver a testear.

**Comment by cynmiks** [comment]
Ok, pero continuan las diferencias en la toolbar. Adjunto imagen.

![cobra - bonificacion_de_intereses - toolbar](https://cloud.githubusercontent.com/assets/19472783/20361201/77d42616-ac15-11e6-900d-b0441e130fe3.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a revisar. Tener en cuenta que los iconos se cambian de formato (ico a gif) y como estandar deben ser de 18x20. Esto provoca que no siempre queden iguales.

**Comment by cynmiks** [comment]
El primer icono se ve grisado, es correcto??

**Comment by rleuzzi** [comment]
Si se le coloco un color símil a la toolbar para evitar se vea el recuadro blanco que tenia el original.

**Comment by cynmiks** [comment]
Ok!
