### ISSUE TITLE
COBRA – cbconcil  – Conciliacion de contratos  

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#267]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Procesos > Conciliación > Conciliación de contratos
Form: cbconcil  
Error: 
• Con CTRL+TAB en la versión 6i, se mueve en la grilla, en cambio en la versión Web, la pantalla desaparce.

Observaciones:

**Comment by rleuzzi** [comment]
En version Web se mueve con CTRL y Flecha Der o Izq

**Comment by cynmiks** [comment]
Recordar que no se debe apretar Ctrl+Tab porque es un shortcut tkey utilizado por el Browser de internet para navegar por las solapas
