### ISSUE TITLE
COBRA – cbreimp – Reimputacion de cobros  

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#268]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Procesos > Reimputacion > Reimportación de cobros
Form: cbreimp
Error: Nos se abre la pantalla del menú.
Observaciones:

**Comment by rleuzzi** [comment]
Testeamos y vemos que abre la pantalla, volver a probar:
![image](https://cloud.githubusercontent.com/assets/14017610/19157535/fe037b9e-8bbb-11e6-84d6-2cabf41195f3.png)

**Comment by cynmiks** [comment]
Testeado OK. Se abre la pantalla. Se aclara que la versión a probar es distinta. Versión Web 1.0 y en Desa 1.2.
