### ISSUE TITLE
COBRA – cbrevrei  – Reversion de Reimputacion 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#269]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Procesos > Reimputacion > Reversión de reimputación
Form: cbrevrei  
Error: No se abre la pantalla del menú.
Observaciones:

**Comment by rleuzzi** [comment]
listo, se ve la pantalla, volver a testear:
![image](https://cloud.githubusercontent.com/assets/14017610/19158584/aff41612-8bbf-11e6-9bd8-bfd046de2257.png)

**Comment by cynmiks** [comment]
Los botones tienen distintos colores.
![cbrevrei - botones](https://cloud.githubusercontent.com/assets/19472783/19194987/f7c6745a-8c85-11e6-9b5f-737803fec8d9.jpg)

Al presionar el botón "Ver Detalle" se abre una pantalla. Al presionar Ctrl + Tab, la pantalla desaparece. En la version 6i el enfoque se va moviendo de celda.
![cbrevrei - pantalla detalle](https://cloud.githubusercontent.com/assets/19472783/19195000/0031a61e-8c86-11e6-847f-726751433535.jpg)

**Comment by rleuzzi** [comment]
Recordar que no se debe apretar Ctrl+Tab porque es un shortcut tkey utilizado por el Browser de internet para navegar por las solapas. En el caso de Forms activa el trigger WHEN-WINDOW-DEACTIVATED.

Los colores de los botones se corrigieron (respetaban la propiedad Current Record Visual Attribute Group del bloque). Volver a testear.

**Comment by cynmiks** [comment]
Testeado OK!
