### ISSUE TITLE
COBRA – Menu Administracion de cheques

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#270]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Procesos > Administracion de cheques
Form: 
Error: No se abre ninguna de las pantallas del menú
![cobra - menu administracion de cheques](https://cloud.githubusercontent.com/assets/19472783/18718534/48c8f460-7ffa-11e6-9ba9-00b6a911bf75.jpg)

Observaciones:

**Comment by rleuzzi** [comment]
Listo, solucionado, volver a testear

**Comment by cynmiks** [comment]
Testeado OK! Se abren las pantallas del menu. Se probarán cada una de las pantallas por separado.
