### ISSUE TITLE
COBRA – cbabmcpa – Liberar cuits de casas particulares 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#271]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Procesos > Recuperos de Cotizaciones > Liberar CUITS Casas Particulares
Form: cbabmcpa
Error: No se abre la pantalla.
Observaciones:

**Comment by rleuzzi** [comment]
Testeamos y abre la pantalla, volver a probar:
![image](https://cloud.githubusercontent.com/assets/14017610/19157645/5ca647d0-8bbc-11e6-8f73-76af59422ac1.png)

**Comment by cynmiks** [comment]
Testeado OK. Se abre la pantalla pero no se puede comparar con la version 6i porque ahora nos se abre en dicha versión.
