### ISSUE TITLE
COBRA – cbabmche  – Ingreso de Cheque 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#285]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Procesos > Administracion de cheques > Ingreso de cheque
Form: cbabmche  
Error: 
• La pantalla no aparece maximizada.
• Al posicionarme en el campo Nro de Cheque no figura la leyenda “Doble click para desplegar la lista de valores”en la barra de estado.
• Al hacer doble click en el campo Nro de Cheque aparece un error.
• La lista de valores de los campos Cliente y Contrato también generan un error.
• La lista de valores del campo Banco es muy grande. Lo mismo ocurre con la lista de valores del campo sucursal.
• Al presionar Ctrl + TAB la pantalla desaparece en cambio en la versión 6i van cambiando el foco del cursor en los distintos campos.

**Comment by rleuzzi** [comment]
1-Listo, no estaba el codigo para maximizar la ventana principal pero se agrego segun solicitud.
2-No existen mas los hit's, en la nueva versión son tooltip y se visualizan en un recuadro amarillo al acercarse al campo.
3-Listo, el query del record group estaba incorrecto proque ordenaba por trunc(f_alta) pero en la consulta se solicitaba el to_char(f_alta, 'dd/mm/yyyy').
4-Idem Anterior.
5-Listo, esto ocurrió porque nos solicitaron agrandar las lov's pequeñas pero en este form el sistema de coordenadas era diferente por ende se agrando de forma incorrecta.
6-Ctrl+Tab no debe usarse en Web porque son teclas reservadas para navegación entre solapas en el Browser. En este caso activa el trigger WHEN-WINDOW-DEACTIVATED.

Volver a testear.

**Comment by cynmiks** [comment]
Se testeo nuevamente: 

1-OK.
2-OK.
3-La LOV del campo Nro de Cheque tiene los datos ordenados de diferentes maneras. Adjunto imagen.

![ingreso_de_cheques - lov clientes](https://cloud.githubusercontent.com/assets/19472783/20358943/99070028-ac0c-11e6-9f25-a3b753be5557.jpg)

4-Idem anterior.
5-OK.
6-Ok.

**Comment by rleuzzi** [comment]
Listo Volver a testear.

**Comment by cynmiks** [comment]
Testeado OK
