### ISSUE TITLE
COBRA – cbconche  – Confirmación de cheque 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#286]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Procesos > Administracion de cheques > Confirmacion de cheque
Form: cbconche  
Error:
• Al presionar Ctrl + TAB la pantalla desaparece en cambio en la versión 6i van cambiando el foco del cursor en los distintos campos.

**Comment by rleuzzi** [comment]
El cambio de campo en version Web se realiza con la tecla TAB solamente

**Comment by cynmiks** [comment]
Desde Sitnergia nos comentan: Si no me equivoco Ctrl+tab se utiliza en Web (Browser) para navegar por las diferentes solapas por lo que en forms se debe utilizar Ctrl+-> para navegar solapas y Tab para navegar por los diferentes campos.
Existe un archivo de configuración de teclas dentro de Weblogic pero no se pueden utilizar combinaciones que utilice por defecto el Browser.
