### ISSUE TITLE
COBRA – cbimpche – Imputación de cheques 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#287]
Ambiente: COBRA
Usuario: APARICIOJ/desaa001
Opción de menú: Procesos > Administración de cheques > Imputación de cheque
Form: cbimpche
Error: 
• No se ve correctamente el nombre del botón
![cbimpche](https://cloud.githubusercontent.com/assets/19472783/19201764/8a3cca72-8ca5-11e6-87c0-edd0b8b08a1d.jpg)

• Al presionar Ctrl + TAB la pantalla desaparece en cambio en la versión 6i van cambiando el foco del cursor en los distintos campos

**Comment by rleuzzi** [comment]
Listo, volver a probar
![image](https://cloud.githubusercontent.com/assets/14017610/19273177/ec3b65ea-8fa1-11e6-9136-7f85fa3a09f8.png)

**Comment by cynmiks** [comment]
Ok. La visualizacion del botón quedó OK. Con respecto al Ctrl + TAB, Rubén nos comenta que:  _Existe un archivo de configuración de teclas dentro de Weblogic pero no se pueden utilizar combinaciones que utilice por defecto el Browser.__  La convinacion Ctrl+tab se utiliza en Web (Browser) para navegar por las diferentes solapas
