### ISSUE TITLE
GLIFE - Tollbar

### ISSUE THREAD

**Issue by jpppina** [jpppina/migracion-galeno-art-forms11g#288]
Ingresando a cualquier form, a la toolbar le falta el icono de ejecutar consulta y el logo está bajo nivel.
Adjunto imagen de como se ve en 6i vs como se ve en Web.
El logo, podría quedar sin rebordes.

![error](https://cloud.githubusercontent.com/assets/13875170/20068174/8accebfc-a4f6-11e6-9860-2e1cceddb4c6.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Ok!
