### ISSUE TITLE
GLIFE - Color de items obligatorios

### ISSUE THREAD

**Issue by jpppina** [jpppina/migracion-galeno-art-forms11g#289]
La aplicación, en general, en el trigger WNFI setea automáticamente mediante la PLL el fondo como amarillo pastel aquellos items que son obligatorios según la definición que se volcó en las propiedades del Item, habría que buscar algún tono similar o el mismo.
Adjunto ejemplo

![error](https://cloud.githubusercontent.com/assets/13875170/20069279/b5e812c2-a4fa-11e6-8b1f-2dbdafd08c0a.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Ok!
