### ISSUE TITLE
GLIFE - Color de botones

### ISSUE THREAD

**Issue by jpppina** [jpppina/migracion-galeno-art-forms11g#290]
Todos los botones deberían ser del tono del fondo de pantalla, actualmente, están más oscuros.
Adjunto ejemplo

![error](https://cloud.githubusercontent.com/assets/13875170/20069547/cc9b497a-a4fb-11e6-995e-cd0303ce8457.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Ok!
