### ISSUE TITLE
GLIFE – LFU_ROLES – Roles de sistema 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#294]
Ambiente: GLIFE
Usuario: XA57062/XA57062desa
Opción de menú: Seguridad > Roles del sistema
Form: LFU_ROLES 
Error: 
•	La letra del frame es distinta. Por favor, ajustarla.

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Ok!
