### ISSUE TITLE
GLIFE – LFU_MENUES – ABM de Menu 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#295]
Ambiente: GLIFE
Usuario: XA57062/XA57062desa
Opción de menú: Seguridad > ABM de menú 
Form: LFU_MENUES
Error: 
•	La letra del frame es distinta. Por favor, ajustarla.

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Ok!
