### ISSUE TITLE
GLIFE – LFI_PARAM_SELLOS – Parametria de sellados 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#296]
Ambiente: GLIFE
Usuario: XA57062/XA57062desa
Opción de menú: Impuestos > Parametrizacion > Impuesto a los sellos
Form: LFI_PARAM_SELLOS
Error: 
•	En la aplicación 6i cuando se abre la pantalla, la grilla aparece con los datos de la consulta realizada. En cambio en la aplicación web, la grilla aparece vacía.
•	La letra del frame es distinta. Por favor, ajustarla.

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Ok!
