### ISSUE TITLE
GLIFE – LFI_DEREMISION – Archivo de derecho de emisión 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#297]
Ambiente: GLIFE
Usuario: XA57062/XA57062desa
Opción de menú: Impuestos > Archivo de derecho de emisión
Form: LFI_DEREMISION
Error: 
•	En la aplicación 6i cuando se abre la pantalla, la grilla aparece con los datos de la consulta realizada. En cambio en la aplicación web, la grilla aparece vacía.
•	La letra del frame es distinta. Por favor, ajustarla.

Observaciones:  --

**Comment by rleuzzi** [comment]
No vemos ninguna grilla. El tipo de font fue modificada a Arial.

**Comment by cynmiks** [comment]
Ok!
