### ISSUE TITLE
GLIFE – LFI_INTERFAZ_GLM – Interfaz contable hacía GLM 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#298]
Ambiente: GLIFE
Usuario: XA57062/XA57062desa
Opción de menú: Interfaces > Interfaz contable hacia GLM
Form: LFI_DEREMISION
Error: 
•	En la aplicación 6i cuando se abre la pantalla, la grilla “Lista de Archivos pendientes” aparece con los datos de la consulta realizada. En cambio en la aplicación web, la grilla aparece vacía.
•	La letra del frame “Contenido de Archivo” es distinta. Por favor, ajustarla.
•	El campo Ruta Destino, ya posse un path de destino por default.

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by cynmiks** [comment]
Se corrigieron los errores antes mencionados pero la pantalla no tiene la misma funcionalidad:
- Se selecciona un archivo de la lista de archivos pendientes, se presiona el botón "Procesar", y en la parte de  Archivo Procesado aparece el resultado del procesamiento. Se preciona el boton ACEPTAR y debería volver a habilitar los botones "Refrescar" y "Procesar" de la parte de Listata de Archivos Pendientes y también debería habilitar el botón de "Ver contenido del archivo"...

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Se habilitan los botones, pero ahora cuando se presiona el botón "Aceptar" aparece el siguiente errror:

![glife](https://cloud.githubusercontent.com/assets/19472783/20564428/0b0bdf54-b16c-11e6-83e5-5bd04b3e7a5b.jpg)

Además, cuando se presiona el botón "Ver contenido del archivo", el cursor en la primera linea aparece al final, en cambio en la versión 6i aparece al principio de la linea.

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Testeado OK!
