### ISSUE TITLE
GLIFE – LFU_PARAMETROS_PATH – Path por default 

### ISSUE THREAD

**Issue by cynmiks** [jpppina/migracion-galeno-art-forms11g#299]
Ambiente: GLIFE
Usuario: XA57062/XA57062desa
Opción de menú: Parametros del sistema > Parametros de paths
Form: LFU_PARAMETROS_PATH
Error: 
•	La letra del frame es distinta. Por favor, ajustarla.

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by cynmiks** [comment]
Ok!
