### ISSUE TITLE
prueba de issue

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#63]
hello word

**Comment by jpppina** [comment]
Respuesta!!!
Ejoy

**Comment by maribadariotti** [comment]
despues me vas a tener que explicar como se usa porque no lo entiendo :-P

**Comment by rleuzzi** [comment]
Estan todos nominados!!!!. Lo que no veo es donde cambiarle el estado si alguien lo descubre avise. Tambien seria importante borrar los issues viejos para arrancar de nuevo de cero.

**Comment by jpppina** [comment]
Se cambia en los Labels
:)
Estoy armando un mail al respecto...

**Comment by maribadariotti** [comment]
un mini manual para todos!! :-)
