### ISSUE TITLE
Cartas mora en desarrollo

### ISSUE THREAD

**Issue by oyuguero** [jpppina/migracion-galeno-art-forms11g#64]
Al ingresar en desarrollo no pide usuario y clave, directamente muestra la primer pantalla sin actualizar el menu del aplicativo. En Test y Produccion funciona bien.

usr: PETTYG 
clave: A1234567

![pantalla_mora](https://cloud.githubusercontent.com/assets/13888057/9635220/be9cdde6-516b-11e5-90a8-002a394a68de.jpg)

**Comment by rleuzzi** [comment]
Quedo una version incorrecta de la libreria fwlogon6. Listo volver a testear

**Comment by oyuguero** [comment]
OK. Se accede correctamente.
