### ISSUE TITLE
nviado y no recepcionado por la sucursal

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#65]
Al intentar imprimir el reporte en WEB genera el siguiente error. 
Opción de menú: Seguimiento de documentación en Tesorería -> Listados -> Enviado y no recepcionado por la sucursal. Dispara el reporte con108.rdf 
Original
![ori_enviado y no recepcionado por la sucursal](https://cloud.githubusercontent.com/assets/13986597/9636447/cc650402-5171-11e5-9287-18cf65022e50.png)
WEB
![web_enviado y no recepcionado por la sucursal](https://cloud.githubusercontent.com/assets/13986597/9636456/d7537dee-5171-11e5-8785-8d6c83f601ad.png)

**Comment by rleuzzi** [comment]
Listo volver a testear. El problema es que el menú enviaba en una global el nombre del reporte con la extensión .rep y ahora en arquitectura web estamos usando el rdf.
