### ISSUE TITLE
Listado de cheques vencidos y a vencer

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#66]
Al intentar imprimir el reporte en WEB genera el siguiente error. 
Opción de menú: Seguimiento de documentación en Tesorería -> Listados -> Listado de cheques vencidos y a vencer. Dispara el reporte con106.rdf
Original
![ori_listado de cheques vencidos y a vencer](https://cloud.githubusercontent.com/assets/13986597/9636547/621bc9fe-5172-11e5-85ef-95fb2c600423.png)
WEB
![web_listado de cheques vencidos y a vencer](https://cloud.githubusercontent.com/assets/13986597/9636554/682e2346-5172-11e5-9479-9dacbd80c4cb.png)

**Comment by rleuzzi** [comment]
Listo volver a testear. El problema es que el menu enviaba en una global el nombre del reporte con la extension .rep y ahora en arquitectura web estamos usando el rdf.
