### ISSUE TITLE
 Reporte de cheques devueltos a Tesorería

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#67]
Al intentar imprimir el reporte en WEB genera el siguiente error. 
Opción de menú: Seguimiento de documentación en Tesorería -> Listados -> Reporte de cheques devueltos a Tesorería. (con111.fmb) y dispara el reporte con111.rdf

Original
![ori_reporte de cheques devueltos a tesoreria](https://cloud.githubusercontent.com/assets/13986597/9638716/87fdf3ac-517e-11e5-8ffe-4122d223eb8e.png)
WEB
![web_reporte de cheques devueltos a tesoreria](https://cloud.githubusercontent.com/assets/13986597/9638730/91ab0624-517e-11e5-9c1b-bf51f321cd71.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear. No tenia visualización de la pll con_lib.pll
