### ISSUE TITLE
Botón con color verde

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#68]
El botón de volver aparece con color.
Opción de menú: Seguimiento de documentación en Tesorería -> Consulta de OP’s

Original
![ori_consulta de op s](https://cloud.githubusercontent.com/assets/13986597/9638795/e04a26b6-517e-11e5-8dc6-8154dd71064f.png)
WEB
![web_consulta de op s](https://cloud.githubusercontent.com/assets/13986597/9638800/e67718f0-517e-11e5-82aa-3d73598ca285.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear. Toma el color del registro actual (así esta configurado el atributo visual) por lo que se coloco color gray al botón.

**Comment by maribadariotti** [comment]
Me volví a loguear y sigue mostrando el botón en color verde

**Comment by rleuzzi** [comment]
Perdon lo habíamos cambiado en la page de cambio de estado. Volver a testear.

**Comment by maribadariotti** [comment]
Rubén... sigue igual, tendré que hacer alguna otra cosa mas que volver a loguearme?

**Comment by rleuzzi** [comment]
No es que le sigue dando prioridad al atributo visual a nivel de bloque. Ahí le agregamos un atributo visual nuevo y lo asociamos a la propiedad Current Record Attribute Property a nivel del item y funciono. Volver a testear.

**Comment by maribadariotti** [comment]
Haora si! gracias
