### ISSUE TITLE
Sucursales

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#69]
Cuando imprimo el reporte nos muestra una ventana de DOS, genera el reporte, vuelve a mostrar la pantalla de DOS y se cierra (todo en cuestión de segundos).
Esto está bien?
Opción de menú: Tablas generales –> Sucursales (con007.fmb)

![web_sucursales](https://cloud.githubusercontent.com/assets/13986597/9640820/ccb1595c-5189-11e5-9183-0f22c1a6a168.png)

**Comment by rleuzzi** [comment]
Si asi funciona la salida por impresora.
