### ISSUE TITLE
Menú principal

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#71]
Al loguearme la pantalla inicial no se visualiza maximizada.
Original
![ori_menu principal](https://cloud.githubusercontent.com/assets/13986597/9665193/fbfd55ce-5244-11e5-9372-66d6719cf417.png)

WEB
![web_menu principal](https://cloud.githubusercontent.com/assets/13986597/9665198/01c291ae-5245-11e5-99e4-6b6ba9d24ded.png)

**Comment by rleuzzi** [comment]
Listo volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente
