### ISSUE TITLE
Ingreso de Fondos 

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#72]
Al buscar una rendición en la lista de valores, en este caso 176, en WEB me arroja error de ítem no navegable, luego otro mensaje de error y finalmente recupera los datos, cosa que no sucede lo mismo en cliente servidor.
Opción de menú: Movimientos -> Ingreso de Fondos (FIP005.fmb)

Original
![ori_ingreso de fondos](https://cloud.githubusercontent.com/assets/13986597/9665573/9b37aec6-5247-11e5-9dbb-c2a5e76df281.png)

WEB
![web_ingreso de fondos](https://cloud.githubusercontent.com/assets/13986597/9665578/a58c9bc0-5247-11e5-92e6-d193cd3179ba.png)
![web_ingreso de fondos2](https://cloud.githubusercontent.com/assets/13986597/9665582/aaa58bb2-5247-11e5-84e3-c3d042683280.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by maribadariotti** [comment]
Funciona correcto
