### ISSUE TITLE
ingreso de fondos

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#73]
Al grabar los movimientos de fondo genera el siguiente error
Opción de menú: Movimientos -> Ingreso de Fondos (FIP005.fmb)
![web_ingreso de fondos3](https://cloud.githubusercontent.com/assets/13986597/9716889/84e97654-5544-11e5-8b27-d1fab8e1d97c.png)

**Comment by maribadariotti** [comment]
Esto se debe probar con nro de rendición 176, y la opción de marcada de Pendientes. Al modificar el "Monto Aprobado" se habilita el botón de "Acepta Fondos", allí cuando queremos aceptar el fondo da el error

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente
