### ISSUE TITLE
Cancelación de Vales de caja

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#74]
Hay alguna forma que los label de los botones se visualicen correctamente?
Opción de menú: Movimientos -> Cancelación de vales de caja (FIP004.fmb
Original
![ori_cancelacion de vales de caja](https://cloud.githubusercontent.com/assets/13986597/9717999/1e36c86c-554e-11e5-807a-682f5a147c6c.png)
)

WEB
![web_cancelacion de vales de caja](https://cloud.githubusercontent.com/assets/13986597/9718004/2a1e29f4-554e-11e5-98cf-532a8b0ca776.png)

**Comment by rleuzzi** [comment]
Ya los agrandamos. Esto si produce por la reconversión del tipo de letra de los labels que hace Oracle y arreglarlos automáticamente podría generar problemas en los otros botones que se visualizan bien. Es mejor que reporten los casos y los corregimos rápidamente sin problemas.

**Comment by maribadariotti** [comment]
Solucionado.
