### ISSUE TITLE
Registro de gastos directos

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#75]
Al intentar agregar un nuevo gasto nos asigna el siguiente error.
Opción de menú: Movimientos -> Registro de gastos directos (FIP002.fmb)
Original (abre un nuevo form)
![ori_registro de gastos directo](https://cloud.githubusercontent.com/assets/13986597/9718168/cb5b9daa-554f-11e5-8b82-f9ec1dc4d32b.png)

WEB
![web_registro de gastos directo](https://cloud.githubusercontent.com/assets/13986597/9718171/d2e1e386-554f-11e5-929b-cb354e740413.png)

**Comment by rleuzzi** [comment]
Listo, había quedado el nombre del fuente en mayúscula y ahora todos están en minúscula pero como Unix es case sensitive no lo veía.

**Comment by maribadariotti** [comment]
Solucionado el tema del form, se ve correctamente.
Quedaría solamente ver el tema de hacer lo mismo que en el form FIP004.fmb con el label de los botones, ya que se visualiza solo la mitad de la leyenda de cada uno.

**Comment by rleuzzi** [comment]
Listo, volver a testear

**Comment by maribadariotti** [comment]
Funciona correctamente.
