### ISSUE TITLE
Registro de gastos de siniestros

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#76]
No abre el form de la opción de menú.
Opción de menú: Movimientos -> Registro de gastos de siniestros (FIP007.fmb)

**Comment by rleuzzi** [comment]
Listo, había quedado sin compilar. Era el fuente que le faltaban los permisos sobre la rtt511 y rtt501 que luego se otorgaron.

**Comment by maribadariotti** [comment]
Ahora se visualiza el form, pero al ingresar genera el siguiente error
![web_registro de gastos de siniestros](https://cloud.githubusercontent.com/assets/13986597/9740235/022426ec-562a-11e5-87bf-fee22b4b298a.png)

Deberia mostrar lo siguiente
![ori_registro de gastos de siniestros](https://cloud.githubusercontent.com/assets/13986597/9740242/0d1199ae-562a-11e5-84d1-e618232ddc62.png)

**Comment by rleuzzi** [comment]
Listo volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente.
