### ISSUE TITLE
Informe de consumo

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#77]
No abre el reporte de la opcion de menú: Informes por Sucursal -> Informe de consumo (FIR003.rdf)
debe mostrar lo siguiente
![ori_informe de consumo](https://cloud.githubusercontent.com/assets/13986597/9718320/244f2b6a-5551-11e5-8070-4a73eaf39093.png)

**Comment by rleuzzi** [comment]
Listo, estos temas van a ir surgiendo porque debemos ir configurando el lanzador para los reportes que se ejecutan directo desde el menú. Este caso ya se encuentra operativo. Volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente
