### ISSUE TITLE
Consumos por conceptos

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#78]
No abre el reporte que llama el form.
Opción de menú: Informes por Sucursal -> Consumos por conceptos form(FIPREP.fmb) y llama al reporte FIR007.rdf

![ori_consumos por conceptos](https://cloud.githubusercontent.com/assets/13986597/9718624/d1f4e5e6-5553-11e5-8429-393b70a52cc9.png)

**Comment by rleuzzi** [comment]
Listo, había un condicional preguntando por la variable :GLOBAL.REPORTE pero el valor venia en minúscula (por el cambio realizado para evitar el case sensitive) y comparaba contra un string en mayúscula. Se les agrego el upper y salio el reporte. Volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente.
