### ISSUE TITLE
Vales no rendidos

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#79]
No abre el reporte de la opción de menú Informes por Sucursal -> Vales no rendidos (FIR004.rdf)
Debe mostrar lo siguiente
![ori_vales no rendidos](https://cloud.githubusercontent.com/assets/13986597/9718917/25d0ed16-5556-11e5-8ca9-f606c4c3827f.png)

**Comment by rleuzzi** [comment]
En la nueva arquitectura estamos utilizando los rdf y no los rep (compilado) porque son incluso mas performantes. El tema es que para que el rdf funcione, los permisos sobre los objetos que utilic el report deben estar correctamente seteados. En este caso, el reporte compila perfectamente con el usario ldrfis pero no asi con el usuario RIADIGOSS (pueden ver en la url 192.168.133.51:8888/reports/rwservlet/showjobs?server=rep_desa que el error es que existen program units descompilados justamente por permisos). Es necesario conseguir la password real de RIADIGOSS (la que conecta a la BD) para poder validar que permiso esta faltando.

**Comment by maribadariotti** [comment]
Corregido... faltaba a esos Procedures crearles sinónimos.
