### ISSUE TITLE
Registracion del presupuesto

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#80]
No abre el form de la opción de menú Procesos -> registración del Presupuesto (FIP014)
![ori_registracion del presupuesto](https://cloud.githubusercontent.com/assets/13986597/9719115/fb305dce-5557-11e5-9ca9-5a4fb95ec633.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente
