### ISSUE TITLE
Listado de cheques entregados

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#81]
No abre el reporte de la opción de menú Seguimiento de Documentación -> Listado de cheques entregados
Debe mostrar lo siguiente
![ori_listado de cheques entregados](https://cloud.githubusercontent.com/assets/13986597/9721559/e0968040-5572-11e5-9c3e-66c5f1540bcf.png)

**Comment by rleuzzi** [comment]
Este caso es el mismo que el comentado donde había un condicional y comparaba mayúscula con minúscula. Ya quedo corregido. Volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente.
