### ISSUE TITLE
Listado de Envíos

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#82]
No abre el reporte en la opción de menú Seguimiento de documentación -> Listado de Envíos y como parámetro de entrada solo debe tener Fecha desde.
Debe mostrar lo siguiente
Original
![ori_listado de envios](https://cloud.githubusercontent.com/assets/13986597/9722197/0d8c1e14-557f-11e5-91fe-edea1fdada76.png)
![ori_listado de envios2](https://cloud.githubusercontent.com/assets/13986597/9722199/119cd4f8-557f-11e5-9250-0d7293731b4a.png)

WEB
![web_listado de envios](https://cloud.githubusercontent.com/assets/13986597/9722200/17367a5e-557f-11e5-82b0-272b71af2f47.png)

**Comment by rleuzzi** [comment]
Listo volver a testear

**Comment by maribadariotti** [comment]
Funciona correctamente.
