### ISSUE TITLE
Glosario FIS

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#83]
No permite acceder al Glosario de FIS el cual accede a una URL de la intranet.
Debe mostrar lo siguiente

![ori_glosario](https://cloud.githubusercontent.com/assets/13986597/9722282/a9c9b7e0-5580-11e5-8c50-d2c178b08587.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente
