### ISSUE TITLE
Arqueo semanal

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#84]
13) Los labels de los campos quedan desacomodados (puede que sea por el tamaño de la letra) y el color de en este caso la fecha queda blanco cuando debería ser un color igual o similar al del canvas.
Opción de menú: Módulo de control -> Arqueo semanal (FIP016.fmb) 
Original
![ori_arqueo semanal](https://cloud.githubusercontent.com/assets/13986597/9736820/dbd9b96c-5619-11e5-9c90-9148fc2b1bd8.png)

WEB
![web_arqueo semanal](https://cloud.githubusercontent.com/assets/13986597/9736828/e2760b04-5619-11e5-9a20-8f0bd061c809.png)

**Comment by rleuzzi** [comment]
Listo volver a testear

**Comment by maribadariotti** [comment]
Sigue igual, salvo que ahora estan todos alineados a la izquierda.
![web_arqueo semanal](https://cloud.githubusercontent.com/assets/13986597/9743163/40bd3ad6-563b-11e5-8974-b959e078725b.png)

**Comment by rleuzzi** [comment]
Al ser cajas de texto el tamaño depende del texto ingresado. Se cargaron espacios en blanco para equiparar las cajas de texto. Volver a revisar.

**Comment by maribadariotti** [comment]
Funciona correctamente
