### ISSUE TITLE
Consumos por Conceptos

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#85]
Se visualiza con asteriscos (*) las fechas en algunos campos, al ejecutar el reporte.
Opción de menú: Listados -> Consumos por Conceptos.
Parámetros para probar -> Selecciono: Cabecera, Fecha desde 20/08/2012, Fecha hasta 20/08/2013
![web_consumos por conceptos](https://cloud.githubusercontent.com/assets/13986597/9772450/bfb1578c-5712-11e5-873e-c7bd045e7069.png)

**Comment by rleuzzi** [comment]
Volver a testear.

**Comment by maribadariotti** [comment]
funciona correctamente
