### ISSUE TITLE
Control de Rendiciones

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#86]
Retomando el tema del reporte que no trae datos en WEB, pero si en cliente servidor te envío prints de pantallas con los parametros que se cargan en el form y los que le llegan al reporte.
![ori_control de rendiciones1](https://cloud.githubusercontent.com/assets/13986597/9817248/1d3b42d0-5878-11e5-91d6-bcfee7d9e059.png)
![ori_control de rendiciones2](https://cloud.githubusercontent.com/assets/13986597/9817252/21784726-5878-11e5-9cea-aa6f0daa2dba.png)
![ori_control de rendiciones3](https://cloud.githubusercontent.com/assets/13986597/9817255/2556b29c-5878-11e5-81ad-daadd7e56f40.png)
![ori_control de rendiciones4](https://cloud.githubusercontent.com/assets/13986597/9817257/282edeae-5878-11e5-89b3-ef5b61abf7d9.png)
![ori_control de rendiciones5](https://cloud.githubusercontent.com/assets/13986597/9817259/2b066250-5878-11e5-9c62-19aee8913ad7.png)

**Comment by rleuzzi** [comment]
En el when-button-press ejecuta el siguiente código antes de llamar al reporte:

 SELECT DECODE(:control.list_estado,'T',1, 
                                       :control.list_estado) 
  INTO vv_estado 
  FROM DUAL;   

Como veras la :control.list_estado es igual a "T" (en la imagen que pones es la listbox Estado del Cierre). Por ende la variable estado es "1" y no null.

Tal vez la versión que migramos no es la indicada, deberían validar eso.

**Comment by maribadariotti** [comment]
Nos podrias enviar por favor el form que tienen uds? porque por lo visto no es el mismo

**Comment by rleuzzi** [comment]
Encontramos el problema. Fue un incorrecto reemplazo en la linea del decode. Ya lo corregimos. Volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente.
