### ISSUE TITLE
Comisiones - Migración a webforms 11g - Cartel despues que termina de generar reports

### ISSUE THREAD

**Issue by adip2002** [jpppina/migracion-galeno-art-forms11g#87]
Por el menú de Comisiones entrando en el submenu Otros -> Reportes Generales los usuarios corren todos los reportes de la aplicación

![image](https://cloud.githubusercontent.com/assets/14348364/9961957/acb1c052-5df9-11e5-84f1-07f463f4f10d.png)

Cuando termina de correr cualquier reporte sale un cartel avisando que se termino de generar el reporte. Este cartel esta saliendo muy grande, por favor ver de achicarlo un poco.

![image](https://cloud.githubusercontent.com/assets/14348364/9961681/31551220-5df8-11e5-94ae-d0311a9d57cb.png)

Para que tengan una referencia de como tendría que salir el cartel les envió una imagen de la versión Client-Server para que observen como sale.

![image](https://cloud.githubusercontent.com/assets/14348364/9962307/62b06fba-5dfb-11e5-86ba-56d65c816d89.png)

**Comment by rleuzzi** [comment]
En Chrome nos sale un mensaje pequeño. Podrian validar si tienen alguna configuracion particular en el browser?. Muchas Gracias.

![reporte](https://cloud.githubusercontent.com/assets/14017610/9967744/ceb8fe42-5e1a-11e5-8923-261c8069b4a1.jpg)

**Comment by adip2002** [comment]
Hola Ruben, como estas? por favor orientame un poco de donde buscar en la configuración del Internet Explorer ya que estuve viendo pero veo que hay muchísimos seteos pero no me oriento sobre que opción modificar para volver a probar y ver si me deja la ventana chica como en el Chrome. Muchas Gracias.

**Comment by rleuzzi** [comment]
Hola, chequea Herramientas->Administrador de extensiones y busca (como muestra la imagen a continuación) el "PDF-Reader". Chequea si esta habilitado o deshabilitado, esto indica si el tamaño lo maneja la extensión de Adobe o directamente el IE. Proba habilitarlo/deshabilitarlo y también habilitarlo, cambiando el tamaño de visualización por defecto en el Adobe.

![pdf_ie](https://cloud.githubusercontent.com/assets/14017610/9999462/eacbea8c-606c-11e5-93da-91819c462a6e.png)

**Comment by adip2002** [comment]
Gracias Rubén, ahí hice el seteo en IE, cuando el Adobe PDF Reader esta deshabilitado luego de correr el reporte y achicar el cartel, de ahi en adelante empieza a salir chico 

![image](https://cloud.githubusercontent.com/assets/14348364/10077142/63afebd4-62b5-11e5-92dd-d261c79ac8d9.png)

![web27](https://cloud.githubusercontent.com/assets/14348364/10077174/8cacec62-62b5-11e5-9131-1d2775f03380.png)

pero cuando el Adobe PDF Reader esta Habilitado el cartel vuelve a salir grande mostrandomelo con el IE.

Entonces, habría que dejar el Adobe PDF Reader deshabilitado? avisame cualquier cosa.

Muchas Gracias

**Comment by rleuzzi** [comment]
Hola, depende de cual sea la configuración estándar en los browser de los usuarios del sistema y si realizar este cambio no afecta la salida de otros reportes en pdf. Revisen esta situación y si es realizar ese cambio en la configuración no es viable, buscamos otra alternativa para este caso. Slds...
