### ISSUE TITLE
Comisiones - Migración a webforms 11g - No se abre el Excel después de generado

### ISSUE THREAD

**Issue by adip2002** [jpppina/migracion-galeno-art-forms11g#88]
Por el menú de Comisiones entrando en el submenu Otros -> Reportes Generales los usuarios corren todos los reportes de la aplicación

![web24](https://cloud.githubusercontent.com/assets/14348364/9962474/42cee298-5dfc-11e5-8969-54b047f5ff1f.png)

Cuando termina de correr cualquier reporte si en la parametrización previa a la generación se parametrizó la opción Abril Excel en Si, no lo esta abriendo automáticamente luego de generado, es decir, luego de copiado desde el servidor al disco c:

En la version CLient-Server lo abre automaticamente luego de generado, aca les dejo una imagen para que lo puedan ver

![image](https://cloud.githubusercontent.com/assets/14348364/9962569/b759459a-5dfc-11e5-8ffe-66e911db6b4d.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by adip2002** [comment]
Listo Ruben, solucionado el problema. Muchas Gracias.
