### ISSUE TITLE
Remitido por suc. Y no recepcionado por tesoreria

### ISSUE THREAD

**Issue by maribadariotti** [jpppina/migracion-galeno-art-forms11g#89]
Al ingresar a la opción de menú, Listados -> Remitido por suc. Y no recepcionado por tesoreria (CON112.fmb) emite el siguiente error y luego continua con la ejecucíon del form

![web_remitido por suc y no recepcionado por tesoreria](https://cloud.githubusercontent.com/assets/13986597/9968367/6c76dba6-5e1e-11e5-9538-89b23e4d7027.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by maribadariotti** [comment]
Funciona correctamente
