### ISSUE TITLE
Diferencia de formato en las columnas fecha en los cvs entre Client-Server y Web

### ISSUE THREAD

**Issue by adip2002** [jpppina/migracion-galeno-art-forms11g#90]
Por el menú de Comisiones yendo a la opción Reportes Generales y ejecutando por ejemplo el reporte Excel de Control de Liquidaciones Temporales

![image](https://cloud.githubusercontent.com/assets/14348364/9995469/7bb5d2b6-6058-11e5-8e5d-c11d4c4d1f27.png)

este genera un archivo csv en el disco c:, abriendo este archivo pasa lo siguiente,

Hay diferencias en el formato de fechas entre los reports que salen en csv desde la web y la versión Cliente-Servidor
En la version Cliente-Servidor las columnas fecha generadas en el csv salen con formato dd/mm/yyyy, esto es debido a que seteamos en el Regedit en HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\ORACLE la variable NLS_DATE_FORMAT con valor dd/mm/yyyy, les paso un ejemplo de como sale

![image](https://cloud.githubusercontent.com/assets/14348364/9995294/bff5d2b0-6057-11e5-9197-da240f7158f6.png)

En la version Web las columnas fecha generadas en el csv salen con formato dd-MON-yyyy, les muestro un ejemplo

![image](https://cloud.githubusercontent.com/assets/14348364/9995353/0e705cda-6058-11e5-9356-dc89047918c1.png)

Los formatos de las columna fecha en los cvs generados en la version Web deberian salir con formato dd/mm/yyyy como salen en la version Client-Server.

Saludos

**Comment by rleuzzi** [comment]
Se creo una variable de entorno para el servidor rep_desa. Por favor testear en ambiente DESA e informar si funciona para poder replicar el cambio en TEST y PROD.

**Comment by adip2002** [comment]
Ruben, hice las pruebas en Desa y ahora si el formato de las fechas en los excel se muestra con formato dd/mm/yyyy, replicar por lo tanto los cambios en los demas ambientes.

![web26](https://cloud.githubusercontent.com/assets/14348364/10074090/2595c9c4-62a4-11e5-8491-f3cbd9c05f42.png)

Muchas Gracias

**Comment by rleuzzi** [comment]
Listo, se replico la configuración en los ambientes de TEST y PROD.

**Comment by adip2002** [comment]
Listo Ruben, hice una prueba recién en Producción y ahora si las fechas salen en los Excel con el formato dd/mm/yyyy.

Muchas Gracias

**Comment by rleuzzi** [comment]
Perfecto, gracias por el aviso. Si podes cerra el issue así ya no aparece como pending. Slds...
