### ISSUE TITLE
Cambio de titulos en window

### ISSUE THREAD

**Issue by oyuguero** [jpppina/migracion-galeno-art-forms11g#91]
El titulo de la pantalla comienza mostrando "Base Corporativa..."

![titulo_1](https://cloud.githubusercontent.com/assets/13888057/10141175/6b551a60-65e1-11e5-9cf0-bafd3a65b608.png)

Luego lo cambia y queda como "ART Manager-Web"
![image](https://cloud.githubusercontent.com/assets/13888057/10141232/ab8611d4-65e1-11e5-912d-ed67b222f528.png)

Y deberia aparecer como el siguiente:
![image](https://cloud.githubusercontent.com/assets/13888057/10141275/fded3060-65e1-11e5-91e5-a8e6bd5b49c5.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by oyuguero** [comment]
Funciona correctamente.
