### ISSUE TITLE
Bloques desalineados

### ISSUE THREAD

**Issue by oyuguero** [jpppina/migracion-galeno-art-forms11g#92]
Quedan desalineados los bloques de datos entre la primer columna y las otras, en ambas solapas de "Tablas Organismos".

![image](https://cloud.githubusercontent.com/assets/13888057/10141941/b8392d36-65e5-11e5-8557-0891d5d4605c.png)
Y en "Otras Parametricas" solapa Datos.
![image](https://cloud.githubusercontent.com/assets/13888057/10141970/efc950dc-65e5-11e5-86c3-5aa8c3e48e8d.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by oyuguero** [comment]
La primer pantalla (Organismos) quedo alineado, pero ahora me doy cuenta que la ventana es muy chica y no entra la barra de desplazamiento (ambas solapas).
La segunda pantalla (Otras parametricas)  sigue sin estár alineada.

**Comment by rleuzzi** [comment]
Volver a testear.

**Comment by oyuguero** [comment]
La segunda pantalla (Otras parametricas) solapa datos de tabla, no esta alineada.

**Comment by rleuzzi** [comment]
Listo volver a testear.

**Comment by oyuguero** [comment]
Probado satisfactoriamente.
