### ISSUE TITLE
Boton muy pequeño

### ISSUE THREAD

**Issue by oyuguero** [jpppina/migracion-galeno-art-forms11g#93]
El boton es muy bajo y queda ajustada la descripcion en "Tablas Conversiones"
![image](https://cloud.githubusercontent.com/assets/13888057/10142031/68e7c26e-65e6-11e5-831c-fe406db529fa.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by oyuguero** [comment]
En la solapa Subregiones el botón también es pequeño

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by oyuguero** [comment]
Corregido.
