### ISSUE TITLE
Iconos para busqueda en toolbar.

### ISSUE THREAD

**Issue by oyuguero** [jpppina/migracion-galeno-art-forms11g#94]
En la toolbar aparece el icono de Búsqueda con una linterna, al seleccionar se puede ingresar el dato a buscar pero no hoy opción de Ejecutar o Cancelar. Creo que están ocultos debajo quizá se debe achicar para que se vean las 3 opciones.

![image](https://cloud.githubusercontent.com/assets/13888057/10142061/a33ac1dc-65e6-11e5-8d6e-66b6e0e5e809.png)
En 6i se muestra así, y el que falta es el de Búsqueda:
![image](https://cloud.githubusercontent.com/assets/13888057/10142141/3cac75ea-65e7-11e5-9097-bfa4c63ae820.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by oyuguero** [comment]
Corregido
