### ISSUE TITLE
Comisiones - Renombra hoja en Excel

### ISSUE THREAD

**Issue by adip2002** [jpppina/migracion-galeno-art-forms11g#97]
En el reporte Excel de Control de Liquidaciones Temporales

![web28](https://cloud.githubusercontent.com/assets/14348364/10668100/fbb2127a-78b0-11e5-8fed-15fa6bb2ce6b.png)

en el Nombre de Archivo el usuario puso Control_Liquid_TMP pero cuando genera el excel por Web a la hoja del Excel le agrega al nombre del archivo que puso el usuario la dirección IP del servidor como muestra la imagen

![web29](https://cloud.githubusercontent.com/assets/14348364/10668414/950dbf40-78b2-11e5-856a-80ca46929e29.png)

se podría sacar esa dirección IP en el nombre de la hoja y dejar el nombre del archivo original que pone el usuario cuando genera el reporte?

**Comment by rleuzzi** [comment]
Hola, agregamos la IP para controlar la concurrencia (dos usuarios que generen el mismo reporte en el mismo tiempo). Dado que bajo arquitectura Web ahora el reporte se genera en el server es necesario cotrolar esta posible problemática.

**Comment by adip2002** [comment]
Ruben, respecto de este tema los usuarios me comentan que tienen Visual Basic programados apuntando a las hojas de los excel, con lo cual si se cambia el nombre de la hoja, ya no la pueden referenciar, hay alguna posibilidad que luego de que copien el excel a la maquina local dejen los nombres de las hojas con el nombre original (sin el IP) o esto es imposible?

**Comment by rleuzzi** [comment]
Ok, si es posible. Lo revisamos y te aviso para que lo pruebes en DESA. Si lo ves correcto publicamos esa versión.

**Comment by adip2002** [comment]
Listo Ruben, avisame y porbamos el cambio en Desa. Muchas Gracias

**Comment by rleuzzi** [comment]
Hola Andres, ya esta la modificación publicada en DESA. Podrás testearla?. No pudimos hacerle la prueba unitaria porque no conocemos mucho los datos. Si detectas algún tema porfa nos comentas y lo vamos corrigiendo. Saludos...

**Comment by adip2002** [comment]
Hola Ruben, así quedo 10 puntos, ya no aparece la dirección IP en el nombre de la hoja de calculo, por favor pasar dichos cambios a Pre y Pro así después le digo al usuario que lo pruebe.

![web31](https://cloud.githubusercontent.com/assets/14348364/11212289/b77e2810-8d13-11e5-9036-cad553924921.png)

Muchas Gracias

**Comment by rleuzzi** [comment]
Andres ya esta publicado en TEST y PROD. Prueben y nos avisn.

Saludos...

**Comment by adip2002** [comment]
Listo, probado satisfactoriamente.
