### ISSUE TITLE
Comisiones - Migración a webforms 11g - No copia reporte generado en disco local y no lo abre una vez generado

### ISSUE THREAD

**Issue by adip2002** [jpppina/migracion-galeno-art-forms11g#98]
Hola Ruben, buen dia.
Cuando el usuario quiere generar un reporte de facturacion pra un periodo determinado no lo esta copiando una vez generado desde el servidor al disco local y por ende una vez copiado no lo puede abrir automaticamente.
Te paso el cartel generado con los parametros y el reporte que se genera

![web32](https://cloud.githubusercontent.com/assets/14348364/11898084/ef0ab9ba-a573-11e5-9c69-0c8185456802.png)

El nombre el report es COLPR014.rdf

En la version Cliente Servidor una vez generdo en el disco c: deberia abrir el excel mostrando la siguiente salida.

![web33](https://cloud.githubusercontent.com/assets/14348364/11898103/1a17ab68-a574-11e5-9614-1693640e2b95.png)

Gracias y cualquier cosa avisame.

Saludos

**Comment by rleuzzi** [comment]
Hola, cuando usas el c:\ como directorio destino es común haya problemas con permisos para grabar a nivel sistema operativo (sobre todo con windows 7) y esto no suele presentarse en la versión cliente servidor porque no hay transferencia de archivo desde el server a la PC. Les pido prueben con el c:\temp u otro como directorio destino y si les funciona ok le pidan a soporte le cambie los permisos para salvar archivos en el c:.

**Comment by adip2002** [comment]
Probe recien de usar el c:\temp y pasa lo mismo.

![web34](https://cloud.githubusercontent.com/assets/14348364/11898930/3bbe9622-a57a-11e5-9478-2aa12aab137a.png)

Pasa solo con este reporte, porque saque otro y lo copia sin ningun problemas desde el servidor al c:\ y luego lo abre normalmente.
Te paso un ejemplo

![web35](https://cloud.githubusercontent.com/assets/14348364/11898944/60feec16-a57a-11e5-994c-42814662ecd1.png)

![web36](https://cloud.githubusercontent.com/assets/14348364/11898948/6598839a-a57a-11e5-9d70-0c511673bc13.png)

Saludos

**Comment by rleuzzi** [comment]
Es en ese solo caso o con todos los reportes que generan excel? Digo porque trabajan con la misma pll y ya lo habían probado no?.

**Comment by adip2002** [comment]
Este problema pasa con este solo reporte. Este reporte trabaja con la pll d2kwutil.pll pero otros que también trabajan con esta librería los copia al c:\ y los abre sin ningún problema, así que no creo que el problema sea esta pll.
Me dice el usuario que es la primera vez que lo prueba y que el problema le pasa con este solo reporte, con los demás no tiene problemas, los copia al c:\ y los abre sin problemas.

Saludos

**Comment by rleuzzi** [comment]
Perfecto ya lo revisamos. Ahora en web ya no usa mas la d2kwutil pero hay que ver cual es el problema porque como bien decís si solo le pasa a este reporte debe ser algo particular. Te cuento en cuanto encontremos el problema.

**Comment by adip2002** [comment]
Listo, gracias. Saludos.

**Comment by rleuzzi** [comment]
Andres, podras volver a ejecutarlo y enviarme un print screen de la consola Java?. Porque los reportes salieron bien (asi lo muestra el log de reportes) pero fallo la descarga por ende fallo webutil y esto queda registrado en la consola de Java.

![image](https://cloud.githubusercontent.com/assets/14017610/11904368/7143974c-a59e-11e5-8db5-18a49ed8e352.png)

**Comment by adip2002** [comment]
Les envió lo solicitado.

![web37](https://cloud.githubusercontent.com/assets/14348364/11905217/ed9b0730-a5a3-11e5-971d-126521bdd307.png)

**Comment by rleuzzi** [comment]
Bueno ahí detectamos el problema. La problemática es porque el nombre del archivo tiene acento. Esto en Linux se transforma en un signo de interrogación entonces no encuentra webutil el archivo a transferir. Prueben quitándole el acento verán que funciona bien. Vemos que los nombres de los archivos están en una tabla de la BD por lo que es recomendable que estandaricen todo a nombres sin acento.

**Comment by adip2002** [comment]
Listo Ruben, ahí funciono, era eso nomas, ya le sacamos los acentos en los nombre de los archivos. Muchas Gracias
